TRUNCATE TABLE public.questions RESTART IDENTITY;

INSERT INTO public.questions (chapter, question_text, options, correct_answer) VALUES
-- ==========================================
-- BAB 1: Kepramukaan Dasar
-- ==========================================
(1, 'Siapakah penulis buku referensi Pramuka "Boyman"?', '["A. -", "B. -", "C. Andri Bob Sunardi", "D. -"]', 'C. Andri Bob Sunardi'),
(1, 'Sifat kepramukaan yang penyelenggaraannya disesuaikan dengan keadaan dan kebutuhan masyarakat di negaranya adalah sifat...', '["A. -", "B. Nasional", "C. -", "D. -"]', 'B. Nasional'),
(1, 'Kepramukaan dapat berlaku untuk siapa saja dan diselenggarakan di mana saja. Ini disebut sifat...', '["A. Universal", "B. -", "C. -", "D. -"]', 'A. Universal'),
(1, 'Kepramukaan harus dapat mengembangkan rasa persaudaraan dan persahabatan antar sesama manusia. Ini adalah cerminan dari sifat...', '["A. -", "B. Internasional", "C. -", "D. -"]', 'B. Internasional'),
(1, 'Fungsi kepramukaan bagi peserta didik (anak/pemuda) pada dasarnya adalah sebagai...', '["A. -", "B. -", "C. Permainan yang menarik", "D. -"]', 'C. Permainan yang menarik'),
(1, 'Bagi orang dewasa, kepramukaan bukan lagi permainan, melainkan suatu tugas yang memerlukan keikhlasan. Ini adalah fungsi sebagai...', '["A. -", "B. Pengabdian", "C. -", "D. -"]', 'B. Pengabdian'),
(1, 'Kepramukaan berfungsi sebagai alat untuk memenuhi kebutuhan dan tujuan masyarakat. Ini adalah fungsi kepramukaan bagi...', '["A. -", "B. -", "C. -", "D. Masyarakat dan Organisasi"]', 'D. Masyarakat dan Organisasi'),
(1, 'Proses pendidikan di luar lingkungan sekolah dan keluarga dalam bentuk kegiatan menarik di alam terbuka disebut...', '["A. -", "B. Kepramukaan", "C. -", "D. -"]', 'B. Kepramukaan'),
(1, 'Orang-orang atau anggota yang mengikuti kegiatan dan tergabung di dalam organisasi kepanduan di Indonesia disebut...', '["A. Pramuka", "B. -", "C. -", "D. -"]', 'A. Pramuka'),
(1, 'Organisasi atau wadah resmi yang menyelenggarakan pendidikan kepramukaan di Indonesia adalah...', '["A. -", "B. -", "C. Gerakan Pramuka", "D. -"]', 'C. Gerakan Pramuka'),
(1, 'Kepanjangan dari PRAMUKA adalah...', '["A. Praja Muda Karana", "B. -", "C. -", "D. -"]', 'A. Praja Muda Karana'),
(1, 'Istilah Praja Muda Karana memiliki arti...', '["A. -", "B. Rakyat muda yang suka berkarya", "C. -", "D. -"]', 'B. Rakyat muda yang suka berkarya'),
(1, 'Bapak Pramuka Indonesia adalah...', '["A. -", "B. -", "C. Sri Sultan Hamengkubuwono IX", "D. -"]', 'C. Sri Sultan Hamengkubuwono IX'),
(1, 'Bapak Pandu Dunia (Chief Scout of the World) adalah...', '["A. Lord Robert Baden Powell", "B. -", "C. -", "D. -"]', 'A. Lord Robert Baden Powell'),
(1, 'Tujuan Gerakan Pramuka yang pertama adalah membentuk anggota pramuka agar memiliki kepribadian yang...', '["A. -", "B. -", "C. Beriman, bertakwa, dan berakhlak mulia", "D. -"]', 'C. Beriman, bertakwa, dan berakhlak mulia'),
(1, 'Tujuan Gerakan Pramuka yang kedua adalah agar anggota pramuka menjadi warga negara yang...', '["A. -", "B. Berjiwa Pancasila", "C. -", "D. -"]', 'B. Berjiwa Pancasila'),
(1, 'Salah satu pilar metode kepramukaan adalah "Learning by Doing", yang artinya...', '["A. -", "B. Belajar sambil melakukan", "C. -", "D. -"]', 'B. Belajar sambil melakukan'),
(1, 'Penggolongan usia Pramuka Siaga adalah...', '["A. 7 - 10 tahun", "B. -", "C. -", "D. -"]', 'A. 7 - 10 tahun'),
(1, 'Penggolongan usia Pramuka Penggalang adalah...', '["A. -", "B. 11 - 15 tahun", "C. -", "D. -"]', 'B. 11 - 15 tahun'),
(1, 'Penggolongan usia Pramuka Penegak adalah...', '["A. -", "B. -", "C. 16 - 20 tahun", "D. -"]', 'C. 16 - 20 tahun'),
(1, 'Penggolongan usia Pramuka Pandega adalah...', '["A. -", "B. -", "C. -", "D. 21 - 25 tahun"]', 'D. 21 - 25 tahun'),
(1, 'Kode Kehormatan bagi Pramuka Siaga terdiri dari...', '["A. -", "B. Dwisatya dan Dwidarma", "C. -", "D. -"]', 'B. Dwisatya dan Dwidarma'),
(1, 'Kode Kehormatan bagi Pramuka Penggalang, Penegak, dan Pandega terdiri dari...', '["A. -", "B. Trisatya dan Dasadarma", "C. -", "D. -"]', 'B. Trisatya dan Dasadarma'),
(1, 'Sistem Pendidikan Kepramukaan menggunakan Sistem Among yang digagas oleh...', '["A. -", "B. -", "C. Ki Hajar Dewantara", "D. -"]', 'C. Ki Hajar Dewantara'),
(1, 'Semboyan Sistem Among di depan memberikan teladan adalah...', '["A. Ing Ngarso Sung Tulodo", "B. -", "C. -", "D. -"]', 'A. Ing Ngarso Sung Tulodo'),
(1, 'Semboyan Sistem Among di tengah membangun kemauan adalah...', '["A. -", "B. Ing Madyo Mangun Karso", "C. -", "D. -"]', 'B. Ing Madyo Mangun Karso'),
(1, 'Semboyan Sistem Among di belakang memberikan dorongan adalah...', '["A. -", "B. -", "C. Tut Wuri Handayani", "D. -"]', 'C. Tut Wuri Handayani'),
(1, 'Satuan terkecil dalam Pramuka Siaga disebut...', '["A. -", "B. -", "C. Barung", "D. -"]', 'C. Barung'),
(1, 'Satuan terkecil dalam Pramuka Penggalang disebut...', '["A. -", "B. Regu", "C. -", "D. -"]', 'B. Regu'),
(1, 'Satuan terkecil dalam Pramuka Penegak disebut...', '["A. -", "B. -", "C. -", "D. Sangga"]', 'D. Sangga'),
(1, 'Satuan terkecil dalam Pramuka Pandega disebut...', '["A. Reka", "B. -", "C. -", "D. -"]', 'A. Reka'),
(1, 'Kumpulan dari beberapa Barung dalam Siaga disebut...', '["A. -", "B. Perindukan", "C. -", "D. -"]', 'B. Perindukan'),
(1, 'Kumpulan dari beberapa Regu dalam Penggalang disebut...', '["A. -", "B. Pasukan", "C. -", "D. -"]', 'B. Pasukan'),
(1, 'Kumpulan dari beberapa Sangga dalam Penegak disebut...', '["A. Ambalan", "B. -", "C. -", "D. -"]', 'A. Ambalan'),
(1, 'Wadah pembinaan Pramuka Pandega di Perguruan Tinggi disebut...', '["A. -", "B. Racana", "C. -", "D. -"]', 'B. Racana'),
(1, 'Tanda kecakapan dalam kepramukaan dibagi menjadi dua, yaitu...', '["A. TKU dan TKK", "B. -", "C. -", "D. -"]', 'A. TKU dan TKK'),
(1, 'TKU singkatan dari...', '["A. -", "B. Tanda Kecakapan Umum", "C. -", "D. -"]', 'B. Tanda Kecakapan Umum'),
(1, 'TKK singkatan dari...', '["A. Tanda Kecakapan Khusus", "B. -", "C. -", "D. -"]', 'A. Tanda Kecakapan Khusus'),
(1, 'Tingkatan TKU pada Pramuka Siaga adalah...', '["A. -", "B. Mula, Bantu, Tata", "C. -", "D. -"]', 'B. Mula, Bantu, Tata'),
(1, 'Tingkatan TKU pada Pramuka Penggalang adalah...', '["A. Ramu, Rakit, Terap", "B. -", "C. -", "D. -"]', 'A. Ramu, Rakit, Terap'),
(1, 'Tingkatan TKU pada Pramuka Penegak adalah...', '["A. Bantara, Laksana", "B. -", "C. -", "D. -"]', 'A. Bantara, Laksana'),
(1, 'Tingkatan TKK (Tanda Kecakapan Khusus) dibagi menjadi 3 tingkatan, yaitu...', '["A. -", "B. -", "C. Purwa, Madya, Utama", "D. -"]', 'C. Purwa, Madya, Utama'),
(1, 'Lambang Gerakan Pramuka Indonesia adalah...', '["A. Tunas Kelapa", "B. -", "C. -", "D. -"]', 'A. Tunas Kelapa'),
(1, 'Pencipta lambang Tunas Kelapa adalah...', '["A. -", "B. Soenardjo Atmodipuro", "C. -", "D. -"]', 'B. Soenardjo Atmodipuro'),
(1, 'Bentuk lambang Pramuka Internasional (WOSM) adalah...', '["A. -", "B. -", "C. Bunga Lily (Fleur-de-lis)", "D. -"]', 'C. Bunga Lily (Fleur-de-lis)'),
(1, 'Gerakan Pramuka resmi diperkenalkan kepada rakyat Indonesia pada tanggal...', '["A. 14 Agustus 1961", "B. -", "C. -", "D. -"]', 'A. 14 Agustus 1961'),
(1, 'Oleh karena itu, Hari Pramuka di Indonesia diperingati setiap tanggal...', '["A. 14 Agustus", "B. -", "C. -", "D. -"]', 'A. 14 Agustus'),
(1, 'Undang-Undang yang mengatur tentang Gerakan Pramuka saat ini adalah...', '["A. -", "B. UU No. 12 Tahun 2010", "C. -", "D. -"]', 'B. UU No. 12 Tahun 2010'),
(1, 'Motto Gerakan Pramuka adalah...', '["A. Satyaku Kudarmakan, Darmaku Kubaktikan", "B. -", "C. -", "D. -"]', 'A. Satyaku Kudarmakan, Darmaku Kubaktikan'),
(1, 'Tingkatan tertinggi dalam setiap golongan Pramuka yang telah memenuhi syarat pencapaian Garuda disebut...', '["A. -", "B. -", "C. Pramuka Garuda", "D. -"]', 'C. Pramuka Garuda'),

-- ==========================================
-- BAB 3: Biografi Baden Powell
-- ==========================================
(3, 'Nama lengkap Bapak Pandu Dunia adalah...', '["A. Robert Stephenson Smyth Baden-Powell", "B. -", "C. -", "D. -"]', 'A. Robert Stephenson Smyth Baden-Powell'),
(3, 'Baden-Powell lahir di kota...', '["A. -", "B. -", "C. London", "D. -"]', 'C. London'),
(3, 'Tanggal lahir Baden-Powell adalah...', '["A. -", "B. 22 Februari 1857", "C. -", "D. -"]', 'B. 22 Februari 1857'),
(3, 'Nama ayah Baden-Powell adalah...', '["A. Prof. Domine Baden-Powell", "B. -", "C. -", "D. -"]', 'A. Prof. Domine Baden-Powell'),
(3, 'Profesi ayah Baden-Powell adalah seorang...', '["A. -", "B. Guru Besar Geometri di Universitas Oxford", "C. -", "D. -"]', 'B. Guru Besar Geometri di Universitas Oxford'),
(3, 'Nama ibu dari Baden-Powell adalah...', '["A. -", "B. -", "C. Miss Henrietta Grace Smyth", "D. -"]', 'C. Miss Henrietta Grace Smyth'),
(3, 'Ayah dari ibu Baden-Powell (kakek dari pihak ibu) adalah seorang laksamana bernama...', '["A. Admiral William T. Smyth", "B. -", "C. -", "D. -"]', 'A. Admiral William T. Smyth'),
(3, 'Ayah Baden-Powell meninggal dunia ketika Baden-Powell berusia...', '["A. 3 tahun", "B. -", "C. -", "D. -"]', 'A. 3 tahun'),
(3, 'Julukan Baden-Powell saat bersekolah di Charterhouse School karena kebiasaannya mandi air dingin adalah...', '["A. -", "B. Bathing Towel", "C. -", "D. -"]', 'B. Bathing Towel'),
(3, 'Kepala sekolah di Charterhouse yang sangat berpengaruh terhadap pembentukan karakter Baden-Powell adalah...', '["A. Dr. Haig Brown", "B. -", "C. -", "D. -"]', 'A. Dr. Haig Brown'),
(3, 'Setelah lulus dari Charterhouse, Baden-Powell mengikuti ujian militer dan lulus kavaleri dengan urutan ke...', '["A. -", "B. Dua", "C. -", "D. -"]', 'B. Dua'),
(3, 'Pasukan kavaleri yang pertama kali ditempati Baden-Powell di India adalah...', '["A. -", "B. -", "C. 13th Hussars", "D. -"]', 'C. 13th Hussars'),
(3, 'Baden-Powell pertama kali ditugaskan ke India sebagai prajurit muda pada tahun...', '["A. 1876", "B. -", "C. -", "D. -"]', 'A. 1876'),
(3, 'Pangkat pertama Baden-Powell saat bergabung di ketentaraan di India adalah...', '["A. -", "B. -", "C. Pembantu Letnan (Sub-Lieutenant)", "D. -"]', 'C. Pembantu Letnan (Sub-Lieutenant)'),
(3, 'Suku Zulu, Ashanti, dan Matabele di Afrika memberikan julukan khusus kepada Baden-Powell, yaitu...', '["A. -", "B. Impeesa", "C. -", "D. -"]', 'B. Impeesa'),
(3, 'Arti dari julukan "Impeesa" yang diberikan oleh suku di Afrika adalah...', '["A. -", "B. -", "C. Serigala yang tidak pernah tidur", "D. -"]', 'C. Serigala yang tidak pernah tidur'),
(3, 'Baden-Powell berhasil mempertahankan sebuah kota dari kepungan bangsa Boer di Afrika Selatan selama 217 hari. Kota tersebut bernama...', '["A. -", "B. -", "C. -", "D. Mafeking"]', 'D. Mafeking'),
(3, 'Peristiwa pengepungan kota Mafeking terjadi pada tahun...', '["A. -", "B. 1899 - 1900", "C. -", "D. -"]', 'B. 1899 - 1900'),
(3, 'Buku panduan pelacakan militer yang ditulis Baden-Powell dan kelak disukai oleh anak-anak muda Inggris adalah...', '["A. -", "B. Aids to Scouting", "C. -", "D. -"]', 'B. Aids to Scouting'),
(3, 'Buku "Aids to Scouting" diterbitkan pada tahun...', '["A. 1899", "B. -", "C. -", "D. -"]', 'A. 1899'),
(3, 'Perkemahan percobaan kepanduan pertama kali diadakan oleh Baden-Powell di sebuah pulau bernama...', '["A. -", "B. Pulau Brownsea", "C. -", "D. -"]', 'B. Pulau Brownsea'),
(3, 'Perkemahan di Pulau Brownsea yang menjadi tonggak sejarah kepramukaan dilaksanakan pada tahun...', '["A. -", "B. 1907", "C. -", "D. -"]', 'B. 1907'),
(3, 'Berapa jumlah anak laki-laki yang mengikuti perkemahan percobaan di Pulau Brownsea?', '["A. -", "B. -", "C. 22 anak", "D. -"]', 'C. 22 anak'),
(3, 'Teman tentara yang membantu Baden-Powell mengurus perkemahan di Pulau Brownsea adalah...', '["A. Mayor Kenneth McLaren", "B. -", "C. -", "D. -"]', 'A. Mayor Kenneth McLaren'),
(3, 'Buku panduan utama yang menjadi cikal bakal berdirinya gerakan kepanduan dunia adalah...', '["A. -", "B. -", "C. Scouting for Boys", "D. -"]', 'C. Scouting for Boys'),
(3, 'Buku "Scouting for Boys" karya Baden-Powell pertama kali diterbitkan pada tahun...', '["A. -", "B. 1908", "C. -", "D. -"]', 'B. 1908'),
(3, 'Organisasi kepanduan putri (Girl Guides) pertama kali dibentuk dengan bantuan adik perempuan Baden-Powell yang bernama...', '["A. -", "B. -", "C. Agnes Baden-Powell", "D. -"]', 'C. Agnes Baden-Powell'),
(3, 'Organisasi Girl Guides (Kepanduan Putri) dirintis pada tahun...', '["A. -", "B. 1910", "C. -", "D. -"]', 'B. 1910'),
(3, 'Kepanduan untuk golongan anak-anak (Siaga/Wolf Cub) didirikan oleh Baden-Powell pada tahun...', '["A. -", "B. -", "C. 1916", "D. -"]', 'C. 1916'),
(3, 'Buku panduan yang digunakan Baden-Powell untuk menginspirasi golongan Siaga (Wolf Cub) adalah...', '["A. -", "B. The Jungle Book", "C. -", "D. -"]', 'B. The Jungle Book'),
(3, 'Penulis buku "The Jungle Book" yang menginspirasi pembentukan golongan Siaga adalah...', '["A. Rudyard Kipling", "B. -", "C. -", "D. -"]', 'A. Rudyard Kipling'),
(3, 'Kepanduan untuk golongan pemuda (Penegak/Rover Scout) dibentuk pada tahun...', '["A. -", "B. 1918", "C. -", "D. -"]', 'B. 1918'),
(3, 'Buku panduan untuk Rover Scout yang ditulis oleh Baden-Powell pada tahun 1922 berjudul...', '["A. -", "B. -", "C. Rovering to Success", "D. -"]', 'C. Rovering to Success'),
(3, 'Jambore Kepanduan Dunia pertama kali diadakan di gedung...', '["A. Olympia Hall", "B. -", "C. -", "D. -"]', 'A. Olympia Hall'),
(3, 'Jambore Dunia pertama diadakan di kota London pada tahun...', '["A. -", "B. 1920", "C. -", "D. -"]', 'B. 1920'),
(3, 'Pada malam terakhir Jambore Dunia pertama, Baden-Powell secara resmi diangkat menjadi...', '["A. -", "B. -", "C. Bapak Pandu Dunia (Chief Scout of the World)", "D. -"]', 'C. Bapak Pandu Dunia (Chief Scout of the World)'),
(3, 'Gelar kehormatan "Lord" (Baron) dianugerahkan kepada Baden-Powell oleh Raja George V pada tahun...', '["A. -", "B. -", "C. 1929", "D. -"]', 'C. 1929'),
(3, 'Nama istri Baden-Powell yang kelak menjadi Chief Guide of the World adalah...', '["A. -", "B. Olave St. Clair Soames", "C. -", "D. -"]', 'B. Olave St. Clair Soames'),
(3, 'Baden-Powell pensiun dari dinas kemiliteran Inggris dengan pangkat terakhir...', '["A. -", "B. Letnan Jenderal", "C. -", "D. -"]', 'B. Letnan Jenderal'),
(3, 'Raja Inggris yang menyarankan Baden-Powell untuk pensiun dari militer agar bisa membesarkan Gerakan Kepanduan adalah...', '["A. -", "B. -", "C. Raja Edward VII", "D. -"]', 'C. Raja Edward VII'),
(3, 'Pada tahun 1919, W. de Bois Maclaren menyumbangkan sebidang tanah untuk pusat pelatihan pembina pramuka yang diberi nama...', '["A. -", "B. -", "C. Gilwell Park", "D. -"]', 'C. Gilwell Park'),
(3, 'Kursus Pembina Pramuka (Wood Badge) pertama kali diselenggarakan di Gilwell Park pada tahun...', '["A. -", "B. 1919", "C. -", "D. -"]', 'B. 1919'),
(3, 'Kalung manik-manik kayu (Wood Badge) berasal dari kalung pimpinan suku Afrika yang pernah dikalahkan oleh Baden-Powell, bernama...', '["A. -", "B. Dinizulu", "C. -", "D. -"]', 'B. Dinizulu'),
(3, 'Simbol dari pusat pelatihan pembina Gilwell Park adalah...', '["A. -", "B. -", "C. Kapak menancap di balok kayu", "D. -"]', 'C. Kapak menancap di balok kayu'),
(3, 'Baden-Powell menghabiskan masa tuanya dan meninggal dunia di negara...', '["A. -", "B. -", "C. -", "D. Kenya"]', 'D. Kenya'),
(3, 'Baden-Powell meninggal dunia pada tanggal...', '["A. 8 Januari 1941", "B. -", "C. -", "D. -"]', 'A. 8 Januari 1941'),
(3, 'Baden-Powell dimakamkan di pemakaman St. Peter, di kota...', '["A. -", "B. -", "C. Nyeri", "D. -"]', 'C. Nyeri'),
(3, 'Usia Baden-Powell saat meninggal dunia adalah...', '["A. -", "B. -", "C. 83 tahun", "D. -"]', 'C. 83 tahun'),
(3, 'Pada batu nisan makam Baden-Powell terdapat tanda jejak kepanduan berupa lingkaran dengan titik di tengah yang memiliki arti...', '["A. Saya telah pulang", "B. -", "C. -", "D. -"]', 'A. Saya telah pulang'),
(3, 'Organisasi kepanduan dunia saat ini bernaung di bawah organisasi bernama WOSM, singkatan dari...', '["A. -", "B. World Organization of the Scout Movement", "C. -", "D. -"]', 'B. World Organization of the Scout Movement'),

-- ==========================================
-- BAB 5: Scouting for Boys
-- ==========================================
(5, 'Bab 5 dalam buku referensi Boyman secara khusus membahas rangkuman dari buku legendaris karya Baden-Powell yang berjudul...', '["A. -", "B. Scouting for Boys", "C. -", "D. -"]', 'B. Scouting for Boys'),
(5, 'Buku Scouting for Boys pada dasarnya dibagi ke dalam beberapa sub-bab yang disebut dengan istilah...', '["A. -", "B. -", "C. Cerita Api Unggun", "D. -"]', 'C. Cerita Api Unggun'),
(5, 'Ada berapa total Cerita Api Unggun (Campfire Yarns) yang menjadi susunan utama materi Scouting for Boys?', '["A. -", "B. -", "C. -", "D. 26 Cerita"]', 'D. 26 Cerita'),
(5, 'Cerita Api Unggun ke-1 membahas sejarah tentang pasukan anak laki-laki di Afrika yang menjadi inspirasi kepanduan, yang disebut...', '["A. Mafeking Cadet Corps", "B. -", "C. -", "D. -"]', 'A. Mafeking Cadet Corps'),
(5, 'Pemimpin pasukan anak-anak pada masa pengepungan Mafeking tersebut adalah...', '["A. -", "B. Lord Edward Cecil", "C. -", "D. -"]', 'B. Lord Edward Cecil'),
(5, 'Baden-Powell menyadari kehebatan pasukan anak-anak di Mafeking yang kemudian menjadi cikal bakal pentingnya peran kaum muda. Pengepungan kota Mafeking terjadi di negara...', '["A. Afrika Selatan", "B. -", "C. -", "D. -"]', 'A. Afrika Selatan'),
(5, 'Cerita Api Unggun ke-4 membahas inti dari sistem kepramukaan yang membagi anggota ke dalam kelompok kecil, disebut dengan...', '["A. -", "B. -", "C. Sistem Regu (Patrol System)", "D. -"]', 'C. Sistem Regu (Patrol System)'),
(5, 'Menurut gagasan awal Baden-Powell, jumlah anggota yang ideal dalam satu regu pramuka (patrol) adalah...', '["A. -", "B. 6 sampai 8 orang", "C. -", "D. -"]', 'B. 6 sampai 8 orang'),
(5, 'Sebutan untuk pemimpin regu dalam bahasa Inggris yang dicetuskan oleh Baden-Powell adalah...', '["A. -", "B. -", "C. -", "D. Patrol Leader"]', 'D. Patrol Leader'),
(5, 'Cerita Api Unggun ke-8 membahas tentang keterampilan membuat bangunan darurat menggunakan kayu dan tali, yang dalam istilah kepramukaan disebut...', '["A. Pionering / Kepeloporan", "B. -", "C. -", "D. -"]', 'A. Pionering / Kepeloporan'),
(5, 'Simpul dasar dalam pionering yang berguna untuk menyambung dua utas tali yang sama besar dan tidak licin adalah...', '["A. Simpul Mati (Reef Knot)", "B. -", "C. -", "D. -"]', 'A. Simpul Mati (Reef Knot)'),
(5, 'Simpul yang berguna untuk mengikat leher binatang agar tidak tercekik, serta sering menjadi simpul dasar penyelamatan adalah...', '["A. -", "B. -", "C. Simpul Tiang (Bowline)", "D. -"]', 'C. Simpul Tiang (Bowline)'),
(5, 'Simpul yang paling sering digunakan untuk memulai dan mengakhiri sebuah ikatan pada tongkat pionering adalah...', '["A. -", "B. Simpul Pangkal (Clove Hitch)", "C. -", "D. -"]', 'B. Simpul Pangkal (Clove Hitch)'),
(5, 'Simpul yang digunakan untuk menyambung dua utas tali yang ukurannya tidak sama besar dan dalam keadaan kering adalah...', '["A. -", "B. -", "C. -", "D. Simpul Anyam (Sheet Bend)"]', 'D. Simpul Anyam (Sheet Bend)'),
(5, 'Ikatan yang digunakan untuk menggabungkan dua buah tongkat yang bersilangan tegak lurus (membentuk sudut 90 derajat) adalah...', '["A. Ikatan Palang (Square Lashing)", "B. -", "C. -", "D. -"]', 'A. Ikatan Palang (Square Lashing)'),
(5, 'Cerita Api Unggun ke-9 membahas mengenai kehidupan di alam terbuka, yaitu rutinitas...', '["A. -", "B. Perkemahan (Camping)", "C. -", "D. -"]', 'B. Perkemahan (Camping)'),
(5, 'Hal yang paling utama dan penting untuk diperhatikan saat memilih lokasi untuk mendirikan tenda perkemahan adalah...', '["A. -", "B. -", "C. Dekat sumber air bersih dan aman dari bahaya alam", "D. -"]', 'C. Dekat sumber air bersih dan aman dari bahaya alam'),
(5, 'Cerita Api Unggun ke-10 memberikan panduan teknis yang sangat dibutuhkan regu mandiri, yaitu tentang...', '["A. Masakan di Perkemahan (Camp Cooking)", "B. -", "C. -", "D. -"]', 'A. Masakan di Perkemahan (Camp Cooking)'),
(5, 'Salah satu makanan khas perkemahan ala Baden-Powell, di mana adonan tepung dililitkan pada sebatang kayu lalu dipanggang di atas bara api, disebut...', '["A. -", "B. Roti Lilit (Twist)", "C. -", "D. -"]', 'B. Roti Lilit (Twist)'),
(5, 'Cerita Api Unggun ke-11 dan 12 mengajarkan keterampilan mengasah kepekaan mata di alam terbuka, berupa...', '["A. -", "B. -", "C. Mencari dan Mengikuti Jejak (Tracking)", "D. -"]', 'C. Mencari dan Mengikuti Jejak (Tracking)'),
(5, 'Saat sedang mengikuti jejak di alam bebas, seorang Pramuka dianjurkan untuk berjalan dengan cara...', '["A. -", "B. -", "C. -", "D. Tenang sambil memperhatikan keadaan tanah dan sekelilingnya"]', 'D. Tenang sambil memperhatikan keadaan tanah dan sekelilingnya'),
(5, 'Dalam sandi jejak Pramuka, susunan batu yang ditumpuk menjadi tiga bagian dan ditambahkan satu batu kecil di sebelah kanan memiliki arti...', '["A. Jalan ke arah kanan", "B. -", "C. -", "D. -"]', 'A. Jalan ke arah kanan'),
(5, 'Sebuah lingkaran yang digambar di tanah dengan titik di tengahnya merupakan tanda jejak kepanduan yang berarti...', '["A. -", "B. -", "C. Saya telah pulang / Kembali ke perkemahan", "D. -"]', 'C. Saya telah pulang / Kembali ke perkemahan'),
(5, 'Cerita Api Unggun ke-13 menuntut seorang pandu untuk memiliki kemampuan observasi dan deduksi. Tokoh detektif fiksi yang sering dijadikan contoh oleh Baden-Powell untuk hal ini adalah...', '["A. -", "B. Sherlock Holmes", "C. -", "D. -"]', 'B. Sherlock Holmes'),
(5, 'Cerita Api Unggun ke-14 berjudul "Menyembunyikan Diri - Mengendap" (Stalking). Mengendap sangat berguna di alam bebas untuk...', '["A. Mendekati dan mengamati hewan liar tanpa disadari oleh hewan tersebut", "B. -", "C. -", "D. -"]', 'A. Mendekati dan mengamati hewan liar tanpa disadari oleh hewan tersebut'),
(5, 'Aturan utama yang harus diperhatikan seorang Pramuka saat sedang mengendap mendekati target di alam liar adalah...', '["A. -", "B. -", "C. Bergerak berlawanan arah dengan hembusan angin", "D. -"]', 'C. Bergerak berlawanan arah dengan hembusan angin'),
(5, 'Cerita Api Unggun ke-15 dan 16 membahas apresiasi terhadap lingkungan hidup, yakni tentang pengetahuan...', '["A. -", "B. Binatang dan Tumbuh-tumbuhan", "C. -", "D. -"]', 'B. Binatang dan Tumbuh-tumbuhan'),
(5, 'Prinsip konservasi dalam kepanduan menyatakan bahwa seorang Pramuka dilarang keras membunuh binatang apa pun, KECUALI...', '["A. -", "B. -", "C. -", "D. Ketika terancam bahaya atau terpaksa untuk bertahan hidup/makan"]', 'D. Ketika terancam bahaya atau terpaksa untuk bertahan hidup/makan'),
(5, 'Pengetahuan seorang Pramuka dalam mengenali berbagai jenis pohon liar, dedaunan, dan akar yang bisa dimakan sangat menunjang kemampuannya dalam bidang...', '["A. Survival (Bertahan Hidup)", "B. -", "C. -", "D. -"]', 'A. Survival (Bertahan Hidup)'),
(5, 'Cerita Api Unggun ke-17 berjudul "Bagaimana Supaya Kuat", yang memberikan instruksi agar kaum muda terbiasa menjaga...', '["A. -", "B. -", "C. Kesehatan fisik dan kebugaran tubuh", "D. -"]', 'C. Kesehatan fisik dan kebugaran tubuh'),
(5, 'Untuk melatih kebugaran tubuh setiap hari, Baden-Powell menyarankan rutinitas senam pagi yang dikenal sebagai...', '["A. -", "B. 6 Latihan Fisik BP (BP Exercises)", "C. -", "D. -"]', 'B. 6 Latihan Fisik BP (BP Exercises)'),
(5, 'Cerita Api Unggun ke-18 dan 19 mengulas tentang kebiasaan yang menyehatkan serta pencegahan penyakit. Baden-Powell sangat mewajibkan pandu bernapas dengan benar melalui...', '["A. Hidung, bukan mulut", "B. -", "C. -", "D. -"]', 'A. Hidung, bukan mulut'),
(5, 'Penyakit yang sering menyerang anggota perkemahan akibat meminum air mentah atau lingkungan perkemahan yang kurang bersih (sanitasi buruk) adalah...', '["A. -", "B. -", "C. -", "D. Diare dan Disentri"]', 'D. Diare dan Disentri'),
(5, 'Cerita Api Unggun ke-20 bertemakan "Sikap Kesatria" (Chivalry). Inspirasi utama Baden-Powell dalam membentuk karakter Pramuka ini berasal dari legenda pahlawan kuno, yaitu...', '["A. -", "B. Kesatria Meja Bundar (Knights of the Round Table)", "C. -", "D. -"]', 'B. Kesatria Meja Bundar (Knights of the Round Table)'),
(5, 'Raja legendaris Inggris yang memimpin para kesatria mulia dalam perumpamaan Baden-Powell tersebut adalah...', '["A. -", "B. -", "C. Raja Arthur", "D. -"]', 'C. Raja Arthur'),
(5, 'Tokoh orang suci pelindung Inggris (Patron Saint) yang juga dijadikan sebagai pelindung simbolis kaum pandu di seluruh dunia karena keberaniannya membunuh naga adalah...', '["A. Santo George (St. George)", "B. -", "C. -", "D. -"]', 'A. Santo George (St. George)'),
(5, 'Hari peringatan St. George, yang sering dirayakan secara internasional oleh anggota Pramuka sebagai ajang pembaruan Janji Pramuka, jatuh pada tanggal...', '["A. -", "B. 23 April", "C. -", "D. -"]', 'B. 23 April'),
(5, 'Cerita Api Unggun ke-21 menekankan pada konsep utama watak yang membuat seorang pandu dihormati, yaitu...', '["A. -", "B. -", "C. Disiplin", "D. -"]', 'C. Disiplin'),
(5, 'Ciri sejati dari kedisiplinan seorang Pramuka saat menerima instruksi dari pimpinannya adalah...', '["A. Mematuhi perintah dan aturan dengan sigap tanpa mengeluh", "B. -", "C. -", "D. -"]', 'A. Mematuhi perintah dan aturan dengan sigap tanpa mengeluh'),
(5, 'Cerita Api Unggun ke-22 berjudul "Memperbaiki Diri". Hal ini mengajarkan filosofi bahwa seorang pandu sejati harus...', '["A. -", "B. -", "C. -", "D. Terus mengasah keahlian dan akhlaknya secara mandiri agar hidupnya lebih berguna"]', 'D. Terus mengasah keahlian dan akhlaknya secara mandiri agar hidupnya lebih berguna'),
(5, 'Cerita Api Unggun ke-23 dan 24 membahas tentang keterampilan vital yang harus dimiliki setiap Pramuka jika terjadi insiden darurat, yakni tentang...', '["A. -", "B. Menyelamatkan Hidup dan Penanganan Kecelakaan (P3K)", "C. -", "D. -"]', 'B. Menyelamatkan Hidup dan Penanganan Kecelakaan (P3K)'),
(5, 'Kaidah terpenting dan pertama kali yang harus dikuasai secara mental saat seorang Pramuka menghadapi situasi kecelakaan parah adalah...', '["A. Tetap tenang dan tidak panik", "B. -", "C. -", "D. -"]', 'A. Tetap tenang dan tidak panik'),
(5, 'Apabila menemui korban yang mengalami pendarahan hebat (luka terbuka memancar), tindakan Pertolongan Pertama yang paling efektif dilakukan adalah...', '["A. -", "B. -", "C. Melakukan tekanan langsung pada area luka / balut tekan", "D. -"]', 'C. Melakukan tekanan langsung pada area luka / balut tekan'),
(5, 'Jika pakaian yang dikenakan oleh seseorang tiba-tiba tersambar api dan terbakar, tindakan penyelematan yang paling tepat diinstruksikan oleh Pramuka adalah...', '["A. -", "B. Menyuruhnya berguling-guling di tanah atau membungkusnya rapat dengan selimut tebal", "C. -", "D. -"]', 'B. Menyuruhnya berguling-guling di tanah atau membungkusnya rapat dengan selimut tebal'),
(5, 'Cerita Api Unggun ke-25 mengingatkan tentang tujuan mulia kehadiran gerakan Pramuka dalam masyarakat, yaitu kewajiban untuk...', '["A. -", "B. -", "C. -", "D. Menolong orang lain di setiap kesempatan"]', 'D. Menolong orang lain di setiap kesempatan'),
(5, 'Sebuah tradisi pandu yang diajarkan oleh Baden-Powell untuk melakukan setidaknya satu kebaikan kecil setiap harinya tanpa mengharap imbalan disebut dengan istilah...', '["A. Good Turn (Berbuat Kebaikan)", "B. -", "C. -", "D. -"]', 'A. Good Turn (Berbuat Kebaikan)'),
(5, 'Cerita Api Unggun ke-26, yang menjadi bab pamungkas dalam materi buku Scouting for Boys, secara umum membahas tentang sikap tanggung jawab bermasyarakat, yakni...', '["A. -", "B. Kewarganegaraan (Citizenship)", "C. -", "D. -"]', 'B. Kewarganegaraan (Citizenship)'),
(5, 'Inti dari jiwa kewarganegaraan seorang Pramuka adalah kemauannya untuk memahami sejarah, pemerintahan, dan hukum bangsanya, agar kelak ia menjadi...', '["A. -", "B. -", "C. Warga negara yang aktif dan bermanfaat bagi negaranya", "D. -"]', 'C. Warga negara yang aktif dan bermanfaat bagi negaranya'),
(5, 'Semboyan kepanduan utama yang diperkenalkan Baden-Powell dalam buku ini, yang wajib dipraktikkan baik dalam kesiapan fisik maupun mental oleh pandu di seluruh dunia adalah...', '["A. Be Prepared (Selalu Siap)", "B. -", "C. -", "D. -"]', 'A. Be Prepared (Selalu Siap)'),
(5, 'Pesan moral secara keseluruhan dari Scouting for Boys yang tercantum di Bab 5 Boyman adalah membentuk remaja agar tidak hanya menjadi sosok petualang alam bebas, tetapi juga menjadi...', '["A. -", "B. -", "C. -", "D. Pria yang bertanggung jawab, mandiri, dan berkarakter mulia"]', 'D. Pria yang bertanggung jawab, mandiri, dan berkarakter mulia'),

-- ==========================================
-- BAB 9: Berkemah / Alam Bebas
-- ==========================================
(9, 'Pengertian berkemah dalam kepramukaan pada dasarnya adalah...', '["A. -", "B. Kegiatan hidup di alam bebas dengan menggunakan tenda sebagai tempat berlindung", "C. -", "D. -"]', 'B. Kegiatan hidup di alam bebas dengan menggunakan tenda sebagai tempat berlindung'),
(9, 'Salah satu sasaran dan motivasi utama dari kegiatan berkemah bagi anggota Pramuka adalah...', '["A. Melatih kemandirian, gotong royong, dan kedisiplinan di alam terbuka", "B. -", "C. -", "D. -"]', 'A. Melatih kemandirian, gotong royong, dan kedisiplinan di alam terbuka'),
(9, 'Tahap pertama yang mutlak harus dilakukan sebelum menyelenggarakan kegiatan perkemahan adalah...', '["A. -", "B. Menyusun Perencanaan dan Persiapan (surat izin, lokasi, anggaran)", "C. -", "D. -"]', 'B. Menyusun Perencanaan dan Persiapan (surat izin, lokasi, anggaran)'),
(9, 'Syarat utama tapak kemah (lokasi perkemahan) yang baik dan aman adalah...', '["A. -", "B. Dekat dengan sumber air yang bersih dan aman dari bahaya alam", "C. -", "D. -"]', 'B. Dekat dengan sumber air yang bersih dan aman dari bahaya alam'),
(9, 'Mengapa mendirikan tenda di dasar cekungan (lembah sempit) sangat dilarang dalam aturan perkemahan?', '["A. -", "B. -", "C. Sangat berbahaya jika terjadi hujan lebat karena rawan banjir bandang/genangan air", "D. -"]', 'C. Sangat berbahaya jika terjadi hujan lebat karena rawan banjir bandang/genangan air'),
(9, 'Mendirikan tenda di bawah pohon tua yang sudah lapuk sangat dihindari karena...', '["A. -", "B. Rawan tertimpa dahan atau pohon tumbang jika ada angin kencang", "C. -", "D. -"]', 'B. Rawan tertimpa dahan atau pohon tumbang jika ada angin kencang'),
(9, 'Arah pintu tenda yang ideal saat didirikan di alam bebas sebaiknya...', '["A. -", "B. Membelakangi atau menyamping dari arah hembusan angin utama", "C. -", "D. -"]', 'B. Membelakangi atau menyamping dari arah hembusan angin utama'),
(9, 'Tujuan utama membuat parit kecil di sekeliling tenda saat berkemah adalah...', '["A. -", "B. -", "C. Mencegah air hujan masuk/menggenangi bagian dalam tenda", "D. -"]', 'C. Mencegah air hujan masuk/menggenangi bagian dalam tenda'),
(9, 'Tenda darurat sementara yang dibuat dari bahan alam atau jas hujan (ponco) dinamakan...', '["A. Bivak", "B. -", "C. -", "D. -"]', 'A. Bivak'),
(9, 'Tenda standar beregu yang sering digunakan oleh Pramuka Penggalang, bentuknya seperti rumah dengan atap segitiga disebut...', '["A. -", "B. -", "C. Tenda Prisma (Tenda Regu)", "D. -"]', 'C. Tenda Prisma (Tenda Regu)'),
(9, 'Agar patok (pasak) tenda menancap kuat menahan tarikan tali, kemiringan pasak yang ditancapkan ke tanah sebaiknya bersudut...', '["A. -", "B. Miring 45-60 derajat berlawanan dengan arah tarikan tali tenda", "C. -", "D. -"]', 'B. Miring 45-60 derajat berlawanan dengan arah tarikan tali tenda'),
(9, 'Simpul yang paling tepat digunakan untuk mengikatkan tali tenda pada pasak agar mudah dikencangkan dan dikendurkan adalah...', '["A. -", "B. -", "C. -", "D. Simpul Tali Tenda (Taut-line Hitch)"]', 'D. Simpul Tali Tenda (Taut-line Hitch)'),
(9, 'Perlengkapan perkemahan dibagi menjadi dua macam, yaitu...', '["A. Perlengkapan Pribadi (Perorangan) dan Perlengkapan Regu (Kelompok)", "B. -", "C. -", "D. -"]', 'A. Perlengkapan Pribadi (Perorangan) dan Perlengkapan Regu (Kelompok)'),
(9, 'Berikut ini yang termasuk ke dalam Perlengkapan Pribadi saat berkemah adalah...', '["A. -", "B. Pakaian ganti, sleeping bag, alat mandi, dan obat pribadi", "C. -", "D. -"]', 'B. Pakaian ganti, sleeping bag, alat mandi, dan obat pribadi'),
(9, 'Berikut ini yang termasuk ke dalam Perlengkapan Regu adalah...', '["A. -", "B. -", "C. Tenda, alat masak regu (nesting), dan kotak P3K regu", "D. -"]', 'C. Tenda, alat masak regu (nesting), dan kotak P3K regu'),
(9, 'Alat pelindung tubuh dari suhu dingin saat tidur di dalam tenda yang bentuknya seperti kepompong disebut...', '["A. -", "B. Sleeping Bag (Kantong Tidur)", "C. -", "D. -"]', 'B. Sleeping Bag (Kantong Tidur)'),
(9, 'Alat berupa alas tidur berbahan busa/spons yang berfungsi menahan hawa dingin dari tanah agar tidak langsung mengenai tubuh disebut...', '["A. -", "B. Matras", "C. -", "D. -"]', 'B. Matras'),
(9, 'Tas besar khusus untuk membawa perlengkapan berkemah yang bentuknya dirancang mengikuti anatomi punggung disebut...', '["A. -", "B. -", "C. Ransel (Carrier / Backpack)", "D. -"]', 'C. Ransel (Carrier / Backpack)'),
(9, 'Prinsip dasar saat melakukan "Packing" (mengepak barang ke dalam ransel) agar tidak membuat punggung cepat lelah adalah...', '["A. -", "B. Barang berat ditaruh di atas, barang ringan di bawah dan menempel punggung", "C. -", "D. -"]', 'B. Barang berat ditaruh di atas, barang ringan di bawah dan menempel punggung'),
(9, 'Selain masalah berat, prinsip "Packing" yang baik untuk melindungi barang dari hujan adalah...', '["A. -", "B. Melapisi bagian dalam ransel dengan kantong plastik sampah (Trash Bag) besar sebelum diisi barang", "C. -", "D. -"]', 'B. Melapisi bagian dalam ransel dengan kantong plastik sampah (Trash Bag) besar sebelum diisi barang'),
(9, 'Jas hujan berukuran besar berbentuk kelelawar yang dapat dialihfungsikan sebagai atap bivak darurat dinamakan...', '["A. -", "B. -", "C. Ponco", "D. -"]', 'C. Ponco'),
(9, 'Syarat bahan makanan yang ideal untuk dibawa saat perkemahan adalah...', '["A. -", "B. Praktis, awet/tahan lama, bernilai gizi tinggi, dan mudah dimasak", "C. -", "D. -"]', 'B. Praktis, awet/tahan lama, bernilai gizi tinggi, dan mudah dimasak'),
(9, 'Alat masak portabel berbahan aluminium yang sering digunakan oleh militer dan pramuka karena bisa disusun menjadi satu wadah ringkas disebut...', '["A. -", "B. -", "C. Nesting", "D. -"]', 'C. Nesting'),
(9, 'Lokasi yang TEPAT untuk menyalakan perapian atau kompor saat berkemah adalah...', '["A. -", "B. -", "C. Di luar tenda pada tempat terbuka dan aman dari tiupan angin kencang atau dedaunan kering", "D. -"]', 'C. Di luar tenda pada tempat terbuka dan aman dari tiupan angin kencang atau dedaunan kering'),
(9, 'Hal yang mutlak DILARANG dilakukan di dalam tenda karena sangat berbahaya adalah...', '["A. Menyalakan api, kompor, lentera minyak, atau lilin", "B. -", "C. -", "D. -"]', 'A. Menyalakan api, kompor, lentera minyak, atau lilin'),
(9, 'Pembuatan fasilitas MCK (Mandi Cuci Kakus) darurat di area kemah harus berjarak minimal...', '["A. -", "B. -", "C. 15-20 meter dari sumber air agar tidak mencemari mata air", "D. -"]', 'C. 15-20 meter dari sumber air agar tidak mencemari mata air'),
(9, 'Manajemen sampah di area perkemahan untuk jenis sampah anorganik (plastik, kaleng, kaca) yang paling benar adalah...', '["A. -", "B. -", "C. -", "D. Dikumpulkan dalam kantong sampah lalu dibawa turun/pulang (Pack it in, Pack it out)"]', 'D. Dikumpulkan dalam kantong sampah lalu dibawa turun/pulang (Pack it in, Pack it out)'),
(9, 'Sampah organik (sisa makanan) di area perkemahan sebaiknya...', '["A. -", "B. Dikubur dalam lubang kecil yang tertutup rapat agak jauh dari tenda agar tidak mengundang hewan", "C. -", "D. -"]', 'B. Dikubur dalam lubang kecil yang tertutup rapat agak jauh dari tenda agar tidak mengundang hewan'),
(9, 'Saat mengambil air minum dari sungai atau mata air alam, langkah wajib yang harus dilakukan sebelum meminumnya adalah...', '["A. -", "B. Disaring dengan kain lalu direbus hingga mendidih (matang) untuk membunuh bakteri", "C. -", "D. -"]', 'B. Disaring dengan kain lalu direbus hingga mendidih (matang) untuk membunuh bakteri'),
(9, 'Api unggun dalam kegiatan perkemahan memiliki fungsi utama sebagai...', '["A. -", "B. Sarana persaudaraan, kehangatan, dan pertunjukan seni", "C. -", "D. -"]', 'B. Sarana persaudaraan, kehangatan, dan pertunjukan seni'),
(9, 'Aturan utama dalam membuat api unggun di alam bebas agar tidak merusak lingkungan adalah...', '["A. -", "B. -", "C. Membuat alas perapian (dari tanah/batu) atau tidak merusak area vegetasi di bawahnya", "D. -"]', 'C. Membuat alas perapian (dari tanah/batu) atau tidak merusak area vegetasi di bawahnya'),
(9, 'Pakaian lapangan yang ideal untuk berkemah adalah...', '["A. -", "B. Pakaian berbahan katun/ripstop yang menyerap keringat, kuat, dan cepat kering (PDL)", "C. -", "D. -"]', 'B. Pakaian berbahan katun/ripstop yang menyerap keringat, kuat, dan cepat kering (PDL)'),
(9, 'Mengapa celana berbahan Jeans/Denim SANGAT TIDAK disarankan dipakai untuk kegiatan kemah di alam bebas?', '["A. -", "B. Berat, tidak menyerap keringat, susah bergerak, dan sangat lama kering jika basah (bisa memicu hipotermia)", "C. -", "D. -"]', 'B. Berat, tidak menyerap keringat, susah bergerak, dan sangat lama kering jika basah (bisa memicu hipotermia)'),
(9, 'Jenis alas kaki yang paling aman untuk kegiatan perkemahan dan penjelajahan adalah...', '["A. -", "B. -", "C. Sepatu lapangan/gunung yang menutupi mata kaki (Boot/Trekking Shoes)", "D. -"]', 'C. Sepatu lapangan/gunung yang menutupi mata kaki (Boot/Trekking Shoes)'),
(9, 'Lembaran kain sintetis kedap air yang sering dipasang di atas tenda untuk menahan air hujan atau dibuat sebagai atap teras dinamakan...', '["A. Flysheet", "B. -", "C. -", "D. -"]', 'A. Flysheet'),
(9, 'Alat kedap air yang diletakkan di bawah (lantai dasar) tenda agar uap air dari tanah tidak tembus ke dalam dinamakan...', '["A. -", "B. Groundsheet / Terpal", "C. -", "D. -"]', 'B. Groundsheet / Terpal'),
(9, 'Aturan keamanan saat memegang dan berjalan membawa senjata tajam (golok/pisau) di perkemahan adalah...', '["A. -", "B. -", "C. Memegang bagian gagang dengan sisi tajam menghadap ke belakang/bawah, atau dimasukkan ke dalam sarungnya", "D. -"]', 'C. Memegang bagian gagang dengan sisi tajam menghadap ke belakang/bawah, atau dimasukkan ke dalam sarungnya'),
(9, 'Saat ada anggota yang bertugas piket jaga malam, posisi jaga yang paling benar adalah...', '["A. -", "B. Berjaga secara bergantian dan tidak jauh dari api/sumber cahaya darurat", "C. -", "D. -"]', 'B. Berjaga secara bergantian dan tidak jauh dari api/sumber cahaya darurat'),
(9, 'Jika tenda bocor parah di tengah hujan badai malam hari dan seluruh pakaian basah kuyup, ancaman kesehatan paling berbahaya adalah...', '["A. -", "B. Hipotermia", "C. -", "D. -"]', 'B. Hipotermia'),
(9, 'Etika perkemahan saat malam hari (Quiet Hours) mengharuskan seluruh anggota untuk...', '["A. Menghentikan aktivitas berisik dan beristirahat agar tidak mengganggu makhluk hidup dan tenda lain", "B. -", "C. -", "D. -"]', 'A. Menghentikan aktivitas berisik dan beristirahat agar tidak mengganggu makhluk hidup dan tenda lain'),
(9, 'Langkah pertama saat akan membongkar tenda di akhir kegiatan kemah adalah...', '["A. -", "B. Mengeluarkan dan membersihkan seluruh barang dari dalam tenda", "C. -", "D. -"]', 'B. Mengeluarkan dan membersihkan seluruh barang dari dalam tenda'),
(9, 'Syarat utama sebelum melipat kain tenda untuk disimpan ke dalam tas adalah...', '["A. -", "B. -", "C. Tenda harus dalam keadaan benar-benar kering agar tidak berjamur", "D. -"]', 'C. Tenda harus dalam keadaan benar-benar kering agar tidak berjamur'),
(9, 'Prinsip pencinta alam "Leave No Trace" (Jangan tinggalkan jejak) mengajarkan kita untuk...', '["A. -", "B. -", "C. Membiarkan kondisi tapak kemah sama bersihnya atau lebih bersih daripada saat kita baru datang", "D. -"]', 'C. Membiarkan kondisi tapak kemah sama bersihnya atau lebih bersih daripada saat kita baru datang'),
(9, 'Kotak atau tas darurat berukuran kecil berisi perlengkapan bertahan hidup esensial (seperti korek anti air, kail pancing, pisau lipat, plester) dinamakan...', '["A. -", "B. Survival Kit", "C. -", "D. -"]', 'B. Survival Kit'),
(9, 'Tindakan yang benar jika tersesat saat melakukan kegiatan penjelajahan di sekitar perkemahan adalah...', '["A. -", "B. STOP (Stop, Think, Observe, Plan) dan tidak panik", "C. -", "D. -"]', 'B. STOP (Stop, Think, Observe, Plan) dan tidak panik'),
(9, 'Fungsi menggunakan pakaian lengan panjang saat menerobos semak/hutan di area kemah adalah...', '["A. -", "B. Menahan dingin, melindungi dari duri, goresan ranting, dan gigitan serangga", "C. -", "D. -"]', 'B. Menahan dingin, melindungi dari duri, goresan ranting, dan gigitan serangga'),
(9, 'Tanda yang dibuat oleh anggota Pramuka menggunakan batu, ranting, atau goresan tanah untuk memberi petunjuk arah di alam bebas disebut...', '["A. -", "B. Tanda Jejak", "C. -", "D. -"]', 'B. Tanda Jejak'),
(9, 'Sikap mental yang paling dituntut dari seorang pemimpin regu saat perkemahan dilanda cuaca buruk adalah...', '["A. -", "B. -", "C. Tenang, mengambil keputusan cepat untuk mengamankan anggota, dan menjaga moral regu", "D. -"]', 'C. Tenang, mengambil keputusan cepat untuk mengamankan anggota, dan menjaga moral regu'),
(9, 'Obat yang wajib dibawa secara pribadi (tidak boleh mengandalkan regu) saat berkemah adalah...', '["A. -", "B. Obat penyakit khusus/alergi yang diidap oleh diri sendiri", "C. -", "D. -"]', 'B. Obat penyakit khusus/alergi yang diidap oleh diri sendiri'),
(9, 'Tujuan akhir setelah kembali dari kegiatan berkemah adalah...', '["A. -", "B. Melakukan evaluasi kegiatan, membersihkan dan merawat kembali peralatan agar siap dipakai di kemudian hari", "C. -", "D. -"]', 'B. Melakukan evaluasi kegiatan, membersihkan dan merawat kembali peralatan agar siap dipakai di kemudian hari'),

-- ==========================================
-- BAB 12: Sandi Morse (Komunikasi)
-- ==========================================
(12, 'Kata "Sandi" berasal dari bahasa Sanskerta, yang memiliki arti...', '["A. -", "B. Rahasia", "C. -", "D. -"]', 'B. Rahasia'),
(12, 'Fungsi utama mempelajari sandi dalam kegiatan kepramukaan adalah untuk...', '["A. -", "B. Melatih daya ingat, kecerdasan, dan ketelitian", "C. -", "D. -"]', 'B. Melatih daya ingat, kecerdasan, dan ketelitian'),
(12, 'Penemu sistem telegraf dan kode Morse adalah seorang seniman dan penemu asal Amerika yang bernama...', '["A. -", "B. Samuel F.B. Morse", "C. -", "D. -"]', 'B. Samuel F.B. Morse'),
(12, 'Kode Morse pertama kali ditemukan dan digunakan secara praktis pada tahun...', '["A. 1837", "B. -", "C. -", "D. -"]', 'A. 1837'),
(12, 'Dalam standar internasional, perbandingan durasi waktu antara bunyi/simbol "titik" dan "garis" pada sandi Morse adalah...', '["A. -", "B. 1 : 3", "C. -", "D. -"]', 'B. 1 : 3'),
(12, 'Huruf yang direpresentasikan dengan satu titik (.) dalam sandi Morse adalah...', '["A. -", "B. E", "C. -", "D. -"]', 'B. E'),
(12, 'Huruf yang direpresentasikan dengan satu garis (-) dalam sandi Morse adalah...', '["A. -", "B. -", "C. T", "D. -"]', 'C. T'),
(12, 'Kode Morse untuk huruf "A" adalah...', '["A. .-", "B. -", "C. -", "D. -"]', 'A. .-'),
(12, 'Kode Morse untuk huruf "B" adalah...', '["A. -...", "B. -", "C. -", "D. -"]', 'A. -...'),
(12, 'Sinyal marabahaya darurat atau minta tolong standar internasional (SOS) dalam sandi Morse ditulis dengan...', '["A. -", "B. ... --- ...", "C. -", "D. -"]', 'B. ... --- ...'),
(12, 'Kode Morse (...--) melambangkan angka...', '["A. -", "B. -", "C. 3", "D. -"]', 'C. 3'),
(12, 'Kode Morse (---..) melambangkan angka...', '["A. -", "B. -", "C. 8", "D. -"]', 'C. 8'),
(12, 'Kode Morse (----.) melambangkan angka...', '["A. -", "B. -", "C. 9", "D. -"]', 'C. 9'),
(12, 'Tanda pemisah antar kata saat menulis sandi Morse di atas kertas biasanya menggunakan tanda...', '["A. -", "B. Garis miring ganda (//)", "C. -", "D. -"]', 'B. Garis miring ganda (//)'),
(12, 'Dalam pengiriman pesan Morse, tanda untuk memulai panggilan atau "Attention" biasanya menggunakan kode...', '["A. -.-.-.", "B. -", "C. -", "D. -"]', 'A. -.-.-.'),
(12, 'Isyarat bahwa "Pesan Selesai" (End of Message) dalam pengiriman Morse ditandai dengan kode gabungan huruf AR, yaitu...', '["A. .-.-.", "B. -", "C. -", "D. -"]', 'A. .-.-.'),
(12, 'Jika pengirim melakukan kesalahan saat mengirim sandi Morse, ia memberikan isyarat salah (E 8 kali) yang berbunyi...', '["A. -", "B. ........", "C. -", "D. -"]', 'B. ........'),
(12, 'Huruf yang secara kode berlawanan dengan A (.-) adalah N, yaitu...', '["A. -.", "B. -", "C. -", "D. -"]', 'A. -.'),
(12, 'Huruf "O" dalam sandi Morse terdiri dari...', '["A. Tiga garis (---)", "B. -", "C. -", "D. -"]', 'A. Tiga garis (---)'),
(12, 'Huruf "S" dalam sandi Morse terdiri dari...', '["A. Tiga titik (...)", "B. -", "C. -", "D. -"]', 'A. Tiga titik (...)'),
(12, 'Gabungan huruf S dan O membentuk kata SOS, yang secara universal berarti isyarat...', '["A. -", "B. Darurat / Marabahaya", "C. -", "D. -"]', 'B. Darurat / Marabahaya'),
(12, 'Huruf "I" dalam sandi Morse terdiri dari...', '["A. -", "B. -", "C. Dua titik (..)", "D. -"]', 'C. Dua titik (..)'),
(12, 'Huruf "M" dalam sandi Morse terdiri dari...', '["A. -", "B. Dua garis (--)", "C. -", "D. -"]', 'B. Dua garis (--)'),
(12, 'Huruf "C" dalam sandi Morse dituliskan dengan kode...', '["A. -.-.", "B. -", "C. -", "D. -"]', 'A. -.-.'),
(12, 'Huruf "D" dalam sandi Morse dituliskan dengan kode...', '["A. -", "B. -..", "C. -", "D. -"]', 'B. -..'),
(12, 'Berlawanan dengan huruf D (-..), huruf "U" dalam sandi morse adalah...', '["A. ..-", "B. -", "C. -", "D. -"]', 'A. ..-'),
(12, 'Huruf "F" dalam sandi Morse adalah...', '["A. ..-.", "B. -", "C. -", "D. -"]', 'A. ..-.'),
(12, 'Huruf "G" dalam sandi Morse adalah...', '["A. -", "B. --.", "C. -", "D. -"]', 'B. --.'),
(12, 'Huruf "H" dalam sandi Morse adalah...', '["A. -", "B. -", "C. -", "D. ...."]', 'D. ....'),
(12, 'Huruf "J" dalam sandi Morse adalah...', '["A. -", "B. -", "C. .---", "D. -"]', 'C. .---'),
(12, 'Huruf "K" dalam sandi Morse adalah...', '["A. -.-", "B. -", "C. -", "D. -"]', 'A. -.-'),
(12, 'Huruf "L" dalam sandi Morse adalah...', '["A. -", "B. .-..", "C. -", "D. -"]', 'B. .-..'),
(12, 'Huruf "P" dalam sandi Morse adalah...', '["A. -", "B. -", "C. .--.", "D. -"]', 'C. .--.'),
(12, 'Huruf "Q" dalam sandi Morse adalah...', '["A. --.-", "B. -", "C. -", "D. -"]', 'A. --.-'),
(12, 'Huruf "R" dalam sandi Morse adalah...', '["A. -", "B. .-.", "C. -", "D. -"]', 'B. .-.'),
(12, 'Huruf "V" dalam sandi Morse adalah...', '["A. -", "B. -", "C. ...-", "D. -"]', 'C. ...-'),
(12, 'Huruf "W" dalam sandi Morse adalah...', '["A. .--", "B. -", "C. -", "D. -"]', 'A. .--'),
(12, 'Huruf "X" dalam sandi Morse adalah...', '["A. -", "B. -..-", "C. -", "D. -"]', 'B. -..-'),
(12, 'Huruf "Y" dalam sandi Morse adalah...', '["A. -", "B. -", "C. -.--", "D. -"]', 'C. -.--'),
(12, 'Huruf "Z" dalam sandi Morse adalah...', '["A. --..", "B. -", "C. -", "D. -"]', 'A. --..'),
(12, 'Angka 1 dalam sandi Morse ditulis dengan urutan...', '["A. -", "B. .----", "C. -", "D. -"]', 'B. .----'),
(12, 'Angka 5 dalam sandi Morse adalah...', '["A. -", "B. -", "C. .....", "D. -"]', 'C. .....'),
(12, 'Angka 0 dalam sandi Morse adalah...', '["A. -----", "B. -", "C. -", "D. -"]', 'A. -----'),
(12, 'Tanda koma (,) dalam tulisan Morse diwakili dengan gabungan...', '["A. -", "B. --..--", "C. -", "D. -"]', 'B. --..--'),
(12, 'Tanda tanya (?) dalam tulisan Morse diwakili dengan gabungan...', '["A. ..--..", "B. -", "C. -", "D. -"]', 'A. ..--..'),
(12, 'Saat mengirim kode Morse dengan peluit, bunyi tiupan pendek secara internasional mewakili...', '["A. Titik", "B. -", "C. -", "D. -"]', 'A. Titik'),
(12, 'Saat mengirim kode Morse dengan peluit, bunyi tiupan panjang yang keras mewakili...', '["A. -", "B. Garis", "C. -", "D. -"]', 'B. Garis'),
(12, 'Isyarat komunikasi "Tunggu" (AS) yang dikirimkan kepada lawan saat transmisi Morse adalah...', '["A. -", "B. -", "C. .-...", "D. -"]', 'C. .-...'),
(12, 'Isyarat "Mengerti / Pesan Diterima" (R) yang dikirimkan kembali oleh penerima pesan adalah...', '["A. .-.", "B. -", "C. -", "D. -"]', 'A. .-.'),
(12, 'Cara paling mudah dan umum yang diajarkan dalam pramuka untuk menghafal sandi Morse adalah metode pengelompokan huruf yang saling...', '["A. -", "B. Berlawanan / Berkebalikan (Contoh: A >< N)", "C. -", "D. -"]', 'B. Berlawanan / Berkebalikan (Contoh: A >< N)'),

-- ==========================================
-- BAB 15: Membaca Peta & Navigasi
-- ==========================================
(15, 'Gambar seluruh atau sebagian permukaan bumi yang diproyeksikan pada bidang datar dengan perbandingan skala tertentu disebut...', '["A. -", "B. Peta", "C. -", "D. -"]', 'B. Peta'),
(15, 'Jenis peta yang sangat penting bagi Pramuka karena menggambarkan tinggi rendahnya permukaan bumi (relief) secara detail adalah...', '["A. -", "B. Peta Topografi", "C. -", "D. -"]', 'B. Peta Topografi'),
(15, 'Kumpulan penjelasan tentang arti simbol-simbol dan warna yang terdapat pada peta disebut...', '["A. -", "B. -", "C. -", "D. Legenda Peta"]', 'D. Legenda Peta'),
(15, 'Angka yang menunjukkan perbandingan antara jarak di atas peta dengan jarak sebenarnya di lapangan disebut...', '["A. -", "B. -", "C. Skala", "D. -"]', 'C. Skala'),
(15, 'Peta dengan skala 1 : 25.000 berarti 1 cm pada peta mewakili jarak sebenarnya di lapangan sejauh...', '["A. -", "B. 250 meter", "C. -", "D. -"]', 'B. 250 meter'),
(15, 'Jika jarak antara titik A dan B di peta topografi (skala 1:50.000) adalah 4 cm, maka jarak sebenarnya di lapangan adalah...', '["A. -", "B. 2 kilometer", "C. -", "D. -"]', 'B. 2 kilometer'),
(15, 'Skala peta yang ditunjukkan dalam bentuk garis lurus yang terbagi menjadi beberapa ruas dengan ukuran satuan jarak tertentu disebut...', '["A. -", "B. -", "C. Skala Garis (Grafis)", "D. -"]', 'C. Skala Garis (Grafis)'),
(15, 'Garis khayal melingkar pada peta topografi yang menghubungkan titik-titik dengan ketinggian yang sama dari permukaan laut disebut...', '["A. -", "B. -", "C. Garis Kontur", "D. -"]', 'C. Garis Kontur'),
(15, 'Ciri khas utama dari garis kontur adalah jika jarak antar garisnya tergambar sangat rapat, hal itu menunjukkan bentuk medan yang...', '["A. -", "B. Curam / Terjal", "C. -", "D. -"]', 'B. Curam / Terjal'),
(15, 'Jika jarak antar garis kontur di peta terlihat renggang atau saling berjauhan, itu menandakan bentuk medan yang...', '["A. -", "B. -", "C. Landai / Datar", "D. -"]', 'C. Landai / Datar'),
(15, 'Garis kontur yang membentuk pola huruf "V" atau "U" terbalik yang menjorok ke arah ketinggian (menunjuk ke tempat yang lebih tinggi) menandakan bentang alam berupa...', '["A. -", "B. Lembah / Aliran Sungai", "C. -", "D. -"]', 'B. Lembah / Aliran Sungai'),
(15, 'Garis kontur yang membentuk pola huruf "V" atau "U" yang menjorok ke arah tempat yang lebih rendah menandakan bentang alam berupa...', '["A. -", "B. Punggungan (Sadel) / Punggung Bukit", "C. -", "D. -"]', 'B. Punggungan (Sadel) / Punggung Bukit'),
(15, 'Garis kontur yang tergambar berupa lingkaran-lingkaran kecil konsentris yang semakin mengecil di bagian tengah biasanya menandakan...', '["A. Puncak bukit / Gunung", "B. -", "C. -", "D. -"]', 'A. Puncak bukit / Gunung'),
(15, 'Jika ada garis kontur melingkar namun memiliki garis-garis rambut kecil (tick marks) yang mengarah ke bagian dalam lingkaran, itu menandakan...', '["A. -", "B. -", "C. Depresi / Kawah / Cekungan", "D. -"]', 'C. Depresi / Kawah / Cekungan'),
(15, 'Selisih ketinggian atau jarak vertikal antara satu garis kontur dengan garis kontur di sebelahnya disebut...', '["A. -", "B. Interval Kontur", "C. -", "D. -"]', 'B. Interval Kontur'),
(15, 'Garis kontur yang biasanya dicetak lebih tebal dan disertai angka penunjuk ketinggian untuk mempermudah pembacaan peta disebut...', '["A. -", "B. -", "C. Indeks Kontur", "D. -"]', 'C. Indeks Kontur'),
(15, 'Sistem garis kisi-kisi (grid) yang membagi peta menjadi kotak-kotak untuk menentukan posisi secara akurat dinamakan koordinat...', '["A. -", "B. -", "C. UTM (Universal Transverse Mercator)", "D. -"]', 'C. UTM (Universal Transverse Mercator)'),
(15, 'Garis vertikal (membujur dari bawah ke atas) pada sistem koordinat kotak (grid) peta yang angkanya dibaca pertama kali (dibaca ke arah Timur) disebut...', '["A. -", "B. Easting", "C. -", "D. -"]', 'B. Easting'),
(15, 'Garis horizontal (melintang dari kiri ke kanan) pada sistem koordinat grid peta yang angkanya dibaca kedua (dibaca ke arah Utara) disebut...', '["A. -", "B. Northing", "C. -", "D. -"]', 'B. Northing'),
(15, 'Aturan emas (golden rule) dalam membaca koordinat grid di atas peta topografi adalah...', '["A. -", "B. -", "C. Baca dari kiri ke kanan (Easting), lalu dari bawah ke atas (Northing)", "D. -"]', 'C. Baca dari kiri ke kanan (Easting), lalu dari bawah ke atas (Northing)'),
(15, 'Jika kita diminta menunjuk titik dengan koordinat 6 digit (contoh: 456 789), ini berarti tingkat ketelitian pencarian lokasi tersebut mencapai area seluas...', '["A. -", "B. 100 meter persegi", "C. -", "D. -"]', 'B. 100 meter persegi'),
(15, 'Arah Utara yang ditunjukkan oleh garis-garis grid vertikal lurus ke atas pada peta disebut...', '["A. -", "B. -", "C. Utara Peta (Grid North)", "D. -"]', 'C. Utara Peta (Grid North)'),
(15, 'Arah Utara yang mengarah tepat ke Kutub Utara bumi (poros rotasi) disebut...', '["A. -", "B. -", "C. Utara Sebenarnya (True North)", "D. -"]', 'C. Utara Sebenarnya (True North)'),
(15, 'Dalam legenda peta topografi standar, warna COKLAT umumnya digunakan untuk menggambarkan...', '["A. -", "B. -", "C. Garis ketinggian (Kontur) dan bentang alam darat", "D. -"]', 'C. Garis ketinggian (Kontur) dan bentang alam darat'),
(15, 'Warna HIJAU pada peta topografi selalu mengindikasikan adanya...', '["A. -", "B. Kawasan vegetasi / Hutan / Perkebunan", "C. -", "D. -"]', 'B. Kawasan vegetasi / Hutan / Perkebunan'),
(15, 'Warna BIRU pada peta digunakan secara universal untuk menyimbolkan unsur...', '["A. -", "B. -", "C. Hidrografi / Perairan (Sungai, danau, rawa, laut)", "D. -"]', 'C. Hidrografi / Perairan (Sungai, danau, rawa, laut)'),
(15, 'Warna MERAH pada peta topografi sering kali dikhususkan untuk menandakan unsur penting buatan manusia, yaitu...', '["A. -", "B. Jalan raya utama / aspal", "C. -", "D. -"]', 'B. Jalan raya utama / aspal'),
(15, 'Warna HITAM dalam peta biasanya digunakan untuk mencetak...', '["A. -", "B. -", "C. Simbol pemukiman, gedung, jalan setapak, dan tulisan", "D. -"]', 'C. Simbol pemukiman, gedung, jalan setapak, dan tulisan'),
(15, 'Simbol berupa titik hitam dengan bentuk segitiga atau lingkaran disertai angka (misal: ▲ 2100) di peta menunjukkan...', '["A. -", "B. Titik Triangulasi / Ketinggian mutlak (Spot Height)", "C. -", "D. -"]', 'B. Titik Triangulasi / Ketinggian mutlak (Spot Height)'),
(15, 'Tindakan menyamakan posisi arah Utara pada peta agar sejajar dengan arah Utara sebenarnya di lapangan (menggunakan kompas) disebut...', '["A. Orientasi Peta", "B. -", "C. -", "D. -"]', 'A. Orientasi Peta'),
(15, 'Syarat pertama yang harus dilakukan sebelum melakukan teknik navigasi Resection atau Intersection di lapangan adalah...', '["A. -", "B. Melakukan Orientasi Peta terlebih dahulu", "C. -", "D. -"]', 'B. Melakukan Orientasi Peta terlebih dahulu'),
(15, 'Teknik navigasi untuk menentukan titik koordinat posisi kita sendiri di atas peta, dengan cara membidik dua objek alam yang sudah diketahui di peta, disebut...', '["A. -", "B. -", "C. Resection", "D. -"]', 'C. Resection'),
(15, 'Teknik navigasi untuk mencari koordinat posisi objek lain (sasaran) yang belum diketahui di peta, dengan membidiknya dari dua titik stasiun yang berbeda, disebut...', '["A. -", "B. Intersection", "C. -", "D. -"]', 'B. Intersection'),
(15, 'Alat ukur sederhana berbentuk busur derajat berbentuk kotak persegi transparan yang digunakan untuk menghitung sudut dan koordinat langsung di atas peta disebut...', '["A. -", "B. -", "C. -", "D. Protractor (Busur Peta)"]', 'D. Protractor (Busur Peta)'),
(15, 'Alat mekanis kecil dengan roda bergerigi yang dijalankan menyusuri rute lengkung di peta (seperti sungai atau jalan berliku) untuk menghitung jarak disebut...', '["A. Curvimeter", "B. -", "C. -", "D. -"]', 'A. Curvimeter'),
(15, 'Penyimpangan sudut yang terjadi antara garis Utara Peta (Grid) dengan Utara Magnetis (Kompas) di suatu wilayah disebut...', '["A. Deklinasi Magnetis", "B. -", "C. -", "D. -"]', 'A. Deklinasi Magnetis'),
(15, 'Jika kita melipat peta topografi untuk dibawa di saku lapangan, cara melipat yang benar agar peta tidak cepat rusak dan mudah dibaca adalah...', '["A. -", "B. -", "C. Dilipat seperti kipas / akordion (zig-zag) dengan bagian yang akan dibaca menghadap luar", "D. -"]', 'C. Dilipat seperti kipas / akordion (zig-zag) dengan bagian yang akan dibaca menghadap luar'),
(15, 'Saat membaca peta, jika kita berjalan mengikuti punggungan bukit (ridge), maka di peta kita sebenarnya sedang melangkah memotong garis-garis kontur yang berbentuk...', '["A. -", "B. U atau V terbalik (menjorok ke bawah)", "C. -", "D. -"]', 'B. U atau V terbalik (menjorok ke bawah)'),
(15, 'Kumpulan peta dalam satu wujud buku besar dinamakan...', '["A. Atlas", "B. -", "C. -", "D. -"]', 'A. Atlas'),
(15, 'Jika tidak memiliki meteran, seorang Pramuka dapat memperkirakan jarak di peta dengan di lapangan menggunakan teknik...', '["A. Menghitung jumlah langkah kaki ganda (Pacing)", "B. -", "C. -", "D. -"]', 'A. Menghitung jumlah langkah kaki ganda (Pacing)'),
(15, 'Garis Khatulistiwa (Equator) yang membelah bumi menjadi Utara dan Selatan ditarik pada derajat...', '["A. 0 derajat lintang", "B. -", "C. -", "D. -"]', 'A. 0 derajat lintang'),
(15, 'Garis Bujur Utama (Prime Meridian) yang menjadi titik 0 derajat dan patokan waktu bumi disepakati melintasi kota...', '["A. -", "B. -", "C. Greenwich, London, Inggris", "D. -"]', 'C. Greenwich, London, Inggris'),
(15, 'Informasi mengenai tahun pembuatan atau pembaruan peta (update) biasanya dapat ditemukan di...', '["A. -", "B. -", "C. Bagian tepi bawah luar / Margin bawah peta", "D. -"]', 'C. Bagian tepi bawah luar / Margin bawah peta'),
(15, 'Navigasi yang dilakukan di malam hari tanpa kompas dapat mengandalkan Rasi Bintang Pari (Crux) untuk menentukan arah...', '["A. -", "B. Selatan", "C. -", "D. -"]', 'B. Selatan'),
(15, 'Navigasi malam hari di belahan bumi utara/tengah dapat menentukan arah Utara dengan mencari konstelasi bintang...', '["A. Ursa Major (Bintang Biduk) / Polaris", "B. -", "C. -", "D. -"]', 'A. Ursa Major (Bintang Biduk) / Polaris'),
(15, 'Alasan mengapa lumut pada pohon lebih sering tumbuh tebal di sisi tertentu (sebagai navigasi darurat penunjuk Timur/Barat) adalah...', '["A. -", "B. Karena sisi tersebut paling sedikit/banyak terkena paparan sinar matahari langsung (kondisi lembap)", "C. -", "D. -"]', 'B. Karena sisi tersebut paling sedikit/banyak terkena paparan sinar matahari langsung (kondisi lembap)'),
(15, 'Metode navigasi alam menggunakan bayangan tongkat kayu yang ditancapkan tegak di tanah pada siang hari disebut metode...', '["A. -", "B. Sundial / Metode Bayangan Matahari", "C. -", "D. -"]', 'B. Sundial / Metode Bayangan Matahari'),
(15, 'Pada peta dengan sistem koordinat grid geografis, Lintang Utara disingkat dengan huruf...', '["A. LU (N - North)", "B. -", "C. -", "D. -"]', 'A. LU (N - North)'),
(15, 'Satu derajat (1°) dalam sistem koordinat Geografis (DMS) dibagi lagi menjadi...', '["A. -", "B. 60 menit", "C. -", "D. -"]', 'B. 60 menit'),
(15, 'Sistem Penentuan Posisi Global yang mengandalkan perangkat elektronik untuk menerima sinyal satelit navigasi bumi disebut...', '["A. -", "B. -", "C. GPS (Global Positioning System)", "D. -"]', 'C. GPS (Global Positioning System)'),

-- ==========================================
-- BAB 20: Macam-Macam Sandi
-- ==========================================
(20, 'Sandi yang menggunakan bentuk garis vertikal, horizontal, dan titik sebagai pengganti huruf disebut...', '["A. -", "B. Sandi Kotak 1", "C. -", "D. -"]', 'B. Sandi Kotak 1'),
(20, 'Sandi Kotak 1 terdiri dari dua macam bentuk pola kerangka dasar, yaitu...', '["A. -", "B. Palang tegak lurus dan silang (X)", "C. -", "D. -"]', 'B. Palang tegak lurus dan silang (X)'),
(20, 'Dalam Sandi Kotak 1, masing-masing ruangan kotak pada kerangka palang maksimal diisi oleh...', '["A. -", "B. 2 huruf", "C. -", "D. -"]', 'B. 2 huruf'),
(20, 'Dalam Sandi Kotak 1, huruf "B" digambarkan dengan bentuk sudut siku-siku terbuka ke atas-kanan, ditambah dengan...', '["A. -", "B. 1 titik", "C. -", "D. -"]', 'B. 1 titik'),
(20, 'Dalam Sandi Kotak 1, huruf "A" digambarkan dengan bentuk sudut siku-siku terbuka ke atas-kanan, ditambah dengan...', '["A. Tanpa titik", "B. -", "C. -", "D. -"]', 'A. Tanpa titik'),
(20, 'Dalam Sandi Kotak 1, huruf "N" yang berada di kerangka silang (X) digambarkan dengan bentuk huruf V yang terbuka ke bawah, ditambah dengan...', '["A. Tanpa titik", "B. -", "C. -", "D. -"]', 'A. Tanpa titik'),
(20, 'Perbedaan utama antara Sandi Kotak 1 dan Sandi Kotak 2 (versi Boyman) terletak pada penempatan huruf, yaitu...', '["A. -", "B. Setiap kotak pada Sandi Kotak 2 berisi 3 huruf dan maksimal menggunakan 2 titik", "C. -", "D. -"]', 'B. Setiap kotak pada Sandi Kotak 2 berisi 3 huruf dan maksimal menggunakan 2 titik'),
(20, 'Dalam Sandi Kotak 2, huruf "C" ditandai dengan kotak yang sama dengan huruf A dan B, namun dibedakan menggunakan...', '["A. -", "B. -", "C. Menggunakan 2 titik", "D. -"]', 'C. Menggunakan 2 titik'),
(20, 'Sandi Kotak 3 memiliki bentuk dasar kerangka yang unik dan sedikit rumit, yaitu berbentuk susunan...', '["A. -", "B. Belah ketupat (segi empat silang)", "C. -", "D. -"]', 'B. Belah ketupat (segi empat silang)'),
(20, 'Sandi Rumput pada dasarnya merupakan bentuk kamuflase atau aplikasi visual murni dari...', '["A. -", "B. -", "C. Sandi Morse", "D. -"]', 'C. Sandi Morse'),
(20, 'Pada Sandi Rumput, lambang titik (.) pada kode morse digambarkan dengan wujud...', '["A. -", "B. Rumput pendek", "C. -", "D. -"]', 'B. Rumput pendek'),
(20, 'Pada Sandi Rumput, lambang garis (-) pada kode morse digambarkan dengan wujud...', '["A. Rumput tinggi", "B. -", "C. -", "D. -"]', 'A. Rumput tinggi'),
(20, 'Sandi yang mengubah urutan abjad sedemikian rupa sehingga abjad dibagi dua, huruf "A" dibaca "N", "B" dibaca "O", dan seterusnya, disebut...', '["A. -", "B. Sandi AN", "C. -", "D. -"]', 'B. Sandi AN'),
(20, 'Kata "PRAMUKA" jika dipecahkan menggunakan rumus abjad Sandi AN akan berbunyi...', '["A. CENZHXN", "B. -", "C. -", "D. -"]', 'A. CENZHXN'),
(20, 'Sandi yang menukar huruf awal alfabet dengan huruf akhir (A menjadi Z, B menjadi Y, C menjadi X) disebut...', '["A. Sandi AZ / Sandi Balik Abjad", "B. -", "C. -", "D. -"]', 'A. Sandi AZ / Sandi Balik Abjad'),
(20, 'Kata "PRAMUKA" jika dibaca ke dalam rumus Sandi AZ maka akan menjadi susunan huruf...', '["A. -", "B. KIZNFPZ", "C. -", "D. -"]', 'B. KIZNFPZ'),
(20, 'Dalam Sandi Angka dasar, di mana A=1, B=2, dst., maka susunan kode 16-18-1-13-21-11-1 dibaca...', '["A. -", "B. -", "C. PRAMUKA", "D. -"]', 'C. PRAMUKA'),
(20, 'Sandi Angka juga bisa divariasikan patokannya (misal awalan A=0). Jika A=0, maka huruf C adalah angka...', '["A. -", "B. -", "C. 2", "D. -"]', 'C. 2'),
(20, 'Sandi yang pengerjaannya menggunakan dua kata kunci yang digabungkan membentuk tabel baris dan kolom persilangan, disebut...', '["A. -", "B. Sandi Koordinat", "C. -", "D. -"]', 'B. Sandi Koordinat'),
(20, 'Dua buah kata yang paling sering dan umum dijadikan kata kunci dalam Sandi Koordinat Pramuka adalah...', '["A. MERAH PUTIH", "B. -", "C. -", "D. -"]', 'A. MERAH PUTIH'),
(20, 'Dalam Sandi Koordinat "MERAH PUTIH", huruf "M" mewakili posisi...', '["A. -", "B. Baris pertama", "C. -", "D. -"]', 'B. Baris pertama'),
(20, 'Sandi yang memanfaatkan patokan interval selisih waktu secara berurutan sebagai pengganti abjad alfabet disebut...', '["A. -", "B. -", "C. Sandi Jam", "D. -"]', 'C. Sandi Jam'),
(20, 'Pada Sandi Jam, jika disepakati pukul 08.00 adalah huruf A, dan interval beda waktu adalah 5 menit, maka huruf B ditulis pada...', '["A. -", "B. 08.05", "C. -", "D. -"]', 'B. 08.05'),
(20, 'Jika pukul 07.00 = A dengan interval waktu yang sama yaitu 5 menit, jam berapakah yang akan menunjukkan huruf C?', '["A. -", "B. 07.10", "C. -", "D. -"]', 'B. 07.10'),
(20, 'Sandi yang mengadopsi cara penulisan unsur rumus kimia, dan sebenarnya merupakan kamuflase lain dari sandi Morse, disebut...', '["A. -", "B. -", "C. Sandi Kimia", "D. -"]', 'C. Sandi Kimia'),
(20, 'Dalam ketentuan Sandi Kimia Pramuka, kelompok huruf Vokal (A, I, U, E, O) berfungsi menggantikan posisi...', '["A. Tanda Titik (.) pada Morse", "B. -", "C. -", "D. -"]', 'A. Tanda Titik (.) pada Morse'),
(20, 'Dalam Sandi Kimia, kelompok huruf Konsonan (B, C, D, F, dst) berfungsi menggantikan posisi...', '["A. -", "B. Tanda Garis (-) pada Morse", "C. -", "D. -"]', 'B. Tanda Garis (-) pada Morse'),
(20, 'Kode Morse ".-" (Huruf A) jika diubah ke dalam Sandi Kimia bisa ditulis menjadi wujud kombinasi Vokal-Konsonan bebas, misalnya...', '["A. OH", "B. -", "C. -", "D. -"]', 'A. OH'),
(20, 'Sandi kata yang cara menyembunyikannya adalah dengan menyisipkan huruf/kata "AND" di antara abjad aslinya disebut...', '["A. -", "B. -", "C. Sandi AND", "D. -"]', 'C. Sandi AND'),
(20, 'Sandi yang bentuk aslinya menyerupai lekukan garis-garis bergelombang tak terputus, di mana lekukan kecil adalah titik dan lekukan besar/runcing adalah garis, dinamakan...', '["A. -", "B. -", "C. -", "D. Sandi Ular / Sandi Gergaji"]', 'D. Sandi Ular / Sandi Gergaji'),
(20, 'Sandi yang cara membacanya sama dengan metode membaca aksara Arab, yaitu dibaca terbalik dari kanan ke kiri, disebut...', '["A. -", "B. -", "C. Sandi Arab", "D. -"]', 'C. Sandi Arab'),
(20, 'Sebuah pesan tertulis "AKUMARP", jika dipecahkan menggunakan kaidah Sandi Arab akan dapat dibaca menjadi kata...', '["A. PRAMUKA", "B. -", "C. -", "D. -"]', 'A. PRAMUKA'),
(20, 'Sandi yang cara membacanya memutar seperti cangkang kerang dari tengah ke luar atau luar ke dalam berlawanan jarum jam disebut...', '["A. -", "B. -", "C. Sandi Siput", "D. -"]', 'C. Sandi Siput'),
(20, 'Sandi yang menggunakan titik-titik timbul untuk membantu penyandang tunanetra membaca, yang diciptakan di Prancis adalah...', '["A. Louis Braille", "B. -", "C. -", "D. -"]', 'A. Louis Braille'),
(20, 'Susunan titik pada Sandi Braille dibentuk berdasarkan pola sebuah kotak imajiner yang berukuran...', '["A. -", "B. 2 kolom dan 3 baris (total 6 titik posisi)", "C. -", "D. -"]', 'B. 2 kolom dan 3 baris (total 6 titik posisi)'),
(20, 'Isyarat komunikasi jarak jauh yang menggunakan peraga sepasang bendera tangan dan sering masuk dalam materi wawasan komunikasi Pramuka disebut...', '["A. -", "B. -", "C. -", "D. Semaphore"]', 'D. Semaphore'),
(20, 'Ukuran standar bendera Semaphore yang biasa digunakan oleh Pramuka Penggalang adalah persegi dengan ukuran...', '["A. 45 x 45 cm", "B. -", "C. -", "D. -"]', 'A. 45 x 45 cm'),
(20, 'Warna standar untuk bendera Semaphore agar mudah terlihat dari jarak jauh adalah perpaduan menyilang dari warna...', '["A. -", "B. Merah dan Kuning", "C. -", "D. -"]', 'B. Merah dan Kuning'),
(20, 'Dalam Sandi Kotak 1, huruf "Z" digambarkan menempati kerangka silang (X) pada sudut bawah dengan ditambahkan...', '["A. -", "B. -", "C. 1 titik", "D. -"]', 'C. 1 titik'),
(20, 'Sandi yang memanipulasi abjad Morse ke dalam bentuk angka pembilang dan penyebut pecahan matematika disebut...', '["A. Sandi Pecahan / Sandi Matematika", "B. -", "C. -", "D. -"]', 'A. Sandi Pecahan / Sandi Matematika'),
(20, 'Pada variasi Sandi Angka, jika disepakati A=3, B=4, maka huruf D akan ditulis menggunakan angka...', '["A. -", "B. 6", "C. -", "D. -"]', 'B. 6'),
(20, 'Huruf "E" dalam kode morse hanya terdiri dari satu titik. Dalam Sandi Kimia, huruf E dapat diwakilkan cukup dengan satu huruf saja, misalnya...', '["A. Huruf Vokal, contohnya O", "B. -", "C. -", "D. -"]', 'A. Huruf Vokal, contohnya O'),
(20, 'Huruf "T" dalam kode morse hanya terdiri dari satu garis. Dalam Sandi Kimia, huruf T dapat diwakilkan cukup dengan satu huruf, misalnya...', '["A. -", "B. Huruf Konsonan, contohnya K", "C. -", "D. -"]', 'B. Huruf Konsonan, contohnya K'),
(20, 'Syarat utama dua buah kata yang akan dijadikan kunci dalam tabel baris/kolom Sandi Koordinat adalah gabungan katanya harus terdiri dari...', '["A. -", "B. -", "C. 10 huruf tanpa ada huruf ganda yang sama", "D. -"]', 'C. 10 huruf tanpa ada huruf ganda yang sama'),
(20, 'Kata "Sandi" itu sendiri berarti...', '["A. -", "B. Rahasia", "C. -", "D. -"]', 'B. Rahasia'),
(20, 'Tujuan asli dibentuknya sandi atau kriptografi pada zaman dahulu yang menginspirasi kepramukaan adalah...', '["A. Mengirim pesan rahasia di masa perang/kritis agar tidak dapat dibaca oleh pihak musuh", "B. -", "C. -", "D. -"]', 'A. Mengirim pesan rahasia di masa perang/kritis agar tidak dapat dibaca oleh pihak musuh'),
(20, 'Jika Sandi Jam dimulai pukul 10.00 = A, dan beda waktu intervalnya dinaikkan menjadi 10 menit, maka pukul 10.20 menunjukkan huruf...', '["A. -", "B. -", "C. C", "D. -"]', 'C. C'),
(20, 'Sandi rahasia unik yang menggunakan bentuk gambar tongkat orang menari dengan posisi lengan berbeda-beda (Dancing Men) terinspirasi dari novel karya...', '["A. Sir Arthur Conan Doyle (Sherlock Holmes)", "B. -", "C. -", "D. -"]', 'A. Sir Arthur Conan Doyle (Sherlock Holmes)'),
(20, '"P-E-M-B-I-N-A" jika ditulis menggunakan rumus Sandi Arab akan menjadi susunan...', '["A. -", "B. A-N-I-B-M-E-P", "C. -", "D. -"]', 'B. A-N-I-B-M-E-P'),
(20, 'Salah satu Syarat Kecakapan Umum (SKU) Pramuka Penggalang mewajibkan anggotanya untuk dapat memahami, membaca, dan mengirimkan pesan isyarat dasar yaitu...', '["A. -", "B. -", "C. Morse dan Semaphore", "D. -"]', 'C. Morse dan Semaphore'),

-- ==========================================
-- BAB 24: P3K & Kesehatan
-- ==========================================
(24, 'Singkatan dari P3K adalah...', '["A. -", "B. Pertolongan Pertama Pada Kecelakaan", "C. -", "D. -"]', 'B. Pertolongan Pertama Pada Kecelakaan'),
(24, 'Tujuan utama dari pemberian P3K adalah...', '["A. -", "B. Menyelamatkan nyawa dan mencegah kondisi korban memburuk", "C. -", "D. -"]', 'B. Menyelamatkan nyawa dan mencegah kondisi korban memburuk'),
(24, 'Langkah pertama yang harus dilakukan saat menemukan korban kecelakaan adalah...', '["A. -", "B. Memastikan keamanan penolong, lokasi, dan korban (Aman Diri)", "C. -", "D. -"]', 'B. Memastikan keamanan penolong, lokasi, dan korban (Aman Diri)'),
(24, 'Pembalut segitiga yang sangat sering digunakan dalam P3K Pramuka disebut...', '["A. -", "B. -", "C. Mitela", "D. -"]', 'C. Mitela'),
(24, 'Alat keras/kaku yang digunakan untuk menahan tulang yang patah agar tidak bergerak disebut...', '["A. -", "B. Bidai / Spalk", "C. -", "D. -"]', 'B. Bidai / Spalk'),
(24, 'Pertolongan pertama pada korban mimisan yang benar adalah...', '["A. -", "B. Menundukkan kepala ke depan dan menjepit cuping hidung", "C. -", "D. -"]', 'B. Menundukkan kepala ke depan dan menjepit cuping hidung'),
(24, 'Pendarahan arteri ditandai dengan ciri-ciri...', '["A. -", "B. Darah memancar seirama denyut jantung dan berwarna merah terang", "C. -", "D. -"]', 'B. Darah memancar seirama denyut jantung dan berwarna merah terang'),
(24, 'Cara menghentikan pendarahan luar yang paling efektif adalah dengan teknik...', '["A. Balut tekan (tekan langsung di atas luka)", "B. -", "C. -", "D. -"]', 'A. Balut tekan (tekan langsung di atas luka)'),
(24, 'Simpul yang digunakan untuk mengakhiri balutan mitela agar mudah dilepas adalah...', '["A. -", "B. Simpul Mati", "C. -", "D. -"]', 'B. Simpul Mati'),
(24, 'Kondisi penurunan suhu tubuh secara drastis akibat cuaca dingin di gunung disebut...', '["A. -", "B. Hipotermia", "C. -", "D. -"]', 'B. Hipotermia'),
(24, 'Pertolongan pertama pada luka bakar ringan (derajat 1) adalah...', '["A. -", "B. Dialiri air bersih mengalir selama 10-15 menit", "C. -", "D. -"]', 'B. Dialiri air bersih mengalir selama 10-15 menit'),
(24, 'Alat untuk mengangkut korban kecelakaan secara darurat yang dibuat dari dua tongkat dan tali disebut...', '["A. -", "B. Tandu Darurat (Dragbar)", "C. -", "D. -"]', 'B. Tandu Darurat (Dragbar)'),
(24, 'Jumlah ikatan minimal pada pemasangan bidai untuk patah tulang tungkai bawah adalah...', '["A. -", "B. -", "C. -", "D. Minimal melewati dua sendi"]', 'D. Minimal melewati dua sendi'),
(24, 'Korban pingsan sebaiknya diposisikan telentang dengan posisi kaki...', '["A. -", "B. -", "C. Lebih tinggi dari kepala (Elevasi)", "D. -"]', 'C. Lebih tinggi dari kepala (Elevasi)'),
(24, 'Isi kotak P3K yang berfungsi untuk membersihkan luka dari kuman adalah...', '["A. -", "B. Antiseptik (Betadine/Rivanol)", "C. -", "D. -"]', 'B. Antiseptik (Betadine/Rivanol)'),
(24, 'Penyakit yang disebabkan oleh gigitan nyamuk Aedes Aegypti adalah...', '["A. -", "B. Demam Berdarah (Dengue)", "C. -", "D. -"]', 'B. Demam Berdarah (Dengue)'),
(24, 'Cara menangani kaki yang terkilir (kram/keseleo) dengan metode RICE, singkatan dari...', '["A. -", "B. Rest, Ice, Compression, Elevation", "C. -", "D. -"]', 'B. Rest, Ice, Compression, Elevation'),
(24, 'Pertolongan pertama jika seseorang tersedak makanan dan sulit bernapas adalah dengan...', '["A. -", "B. Manuver Heimlich (hentakan pada perut)", "C. -", "D. -"]', 'B. Manuver Heimlich (hentakan pada perut)'),
(24, 'Obat yang digunakan untuk mengurangi rasa sakit kepala atau demam ringan adalah...', '["A. -", "B. Parasetamol", "C. -", "D. -"]', 'B. Parasetamol'),
(24, 'Untuk mengganti cairan tubuh yang hilang akibat diare, sebaiknya diberikan...', '["A. -", "B. Oralit", "C. -", "D. -"]', 'B. Oralit'),
(24, 'Pembalutan pada luka di kepala biasanya menggunakan mitela yang dilipat menjadi bentuk...', '["A. -", "B. Segitiga terbuka", "C. -", "D. -"]', 'B. Segitiga terbuka'),
(24, 'Luka yang disebabkan oleh benda tumpul dan menyebabkan memar kebiruan disebut luka...', '["A. -", "B. Luka Memar (Contusio)", "C. -", "D. -"]', 'B. Luka Memar (Contusio)'),
(24, 'Tindakan RJP (Resusitasi Jantung Paru) dilakukan pada korban yang...', '["A. -", "B. Henti napas dan henti jantung", "C. -", "D. -"]', 'B. Henti napas dan henti jantung'),
(24, 'Pada saat memindahkan korban dengan tandu, posisi kepala korban sebaiknya berada di...', '["A. -", "B. Belakang (berlawanan arah jalan)", "C. -", "D. -"]', 'B. Belakang (berlawanan arah jalan)'),
(24, 'Warna kotak P3K standar biasanya adalah...', '["A. -", "B. Putih dengan tanda palang merah/hijau", "C. -", "D. -"]', 'B. Putih dengan tanda palang merah/hijau'),
(24, 'Pertolongan pertama pada gigitan ular yang paling tepat adalah...', '["A. -", "B. -", "C. Imobilisasi (tidak menggerakkan bagian yang digigit) dan bawa ke RS", "D. -"]', 'C. Imobilisasi (tidak menggerakkan bagian yang digigit) dan bawa ke RS'),
(24, 'Pembalut elastis (Elastic Bandage) sangat baik digunakan untuk menangani...', '["A. -", "B. Terkilir / Cedera sendi", "C. -", "D. -"]', 'B. Terkilir / Cedera sendi'),
(24, 'Penyakit yang sering muncul di perkemahan akibat sanitasi buruk dan air kotor adalah...', '["A. -", "B. Diare", "C. -", "D. -"]', 'B. Diare'),
(24, 'Kasa steril diletakkan langsung di atas luka bertujuan untuk...', '["A. -", "B. Menutup luka agar tidak infeksi dan menyerap darah", "C. -", "D. -"]', 'B. Menutup luka agar tidak infeksi dan menyerap darah'),
(24, 'Berapa jumlah penolong yang ideal untuk mengangkat tandu darurat?', '["A. -", "B. 2-4 orang", "C. -", "D. -"]', 'B. 2-4 orang'),
(24, 'Alat untuk mengukur suhu tubuh manusia disebut...', '["A. -", "B. Termometer", "C. -", "D. -"]', 'B. Termometer'),
(24, 'Suhu tubuh normal manusia berkisar antara...', '["A. -", "B. 36-37 derajat", "C. -", "D. -"]', 'B. 36-37 derajat'),
(24, 'Tindakan yang harus dihindari saat menolong korban patah tulang adalah...', '["A. -", "B. Mencoba meluruskan posisi tulang secara paksa", "C. -", "D. -"]', 'B. Mencoba meluruskan posisi tulang secara paksa'),
(24, 'Mencuci tangan sebelum makan dan setelah beraktivitas merupakan contoh...', '["A. -", "B. Perilaku Hidup Bersih dan Sehat (PHBS)", "C. -", "D. -"]', 'B. Perilaku Hidup Bersih dan Sehat (PHBS)'),
(24, 'Cairan yang digunakan untuk mencuci mata jika kemasukan debu adalah...', '["A. -", "B. Air bersih / Boorwater", "C. -", "D. -"]', 'B. Air bersih / Boorwater'),
(24, 'Pembalut Mitela dilipat menjadi "Gendongan" berfungsi untuk menyangga cedera pada...', '["A. -", "B. Lengan / Bahu", "C. -", "D. -"]', 'B. Lengan / Bahu'),
(24, 'Tanda-tanda seseorang mengalami syok (shock) adalah...', '["A. -", "B. Nadi cepat dan lemah, kulit pucat, keringat dingin", "C. -", "D. -"]', 'B. Nadi cepat dan lemah, kulit pucat, keringat dingin'),
(24, 'Zat racun dalam makanan dapat dinetralkan sementara (sebelum ke dokter) dengan meminum...', '["A. Susu / Air kelapa", "B. -", "C. -", "D. -"]', 'A. Susu / Air kelapa'),
(24, 'Obat luar yang digunakan untuk meredakan gatal akibat gigitan serangga adalah...', '["A. -", "B. Minyak Kayu Putih / Kaladin", "C. -", "D. -"]', 'B. Minyak Kayu Putih / Kaladin'),
(24, 'Luka tusuk akibat paku berkarat sangat berisiko menyebabkan penyakit...', '["A. -", "B. Tetanus", "C. -", "D. -"]', 'B. Tetanus'),
(24, 'Pada RJP (CPR), rasio kompresi dada dan napas buatan untuk satu penolong adalah...', '["A. -", "B. 30 : 2", "C. -", "D. -"]', 'B. 30 : 2'),
(24, 'Pembalutan luka di lutut yang sedang ditekuk paling baik menggunakan teknik...', '["A. Balutan angka delapan", "B. -", "C. -", "D. -"]', 'A. Balutan angka delapan'),
(24, 'Bagian dari tas P3K yang digunakan untuk memotong perban atau pakaian korban adalah...', '["A. -", "B. Gunting", "C. -", "D. -"]', 'B. Gunting'),
(24, 'Untuk membersihkan luka yang kotor dari kerikil atau pasir digunakan...', '["A. -", "B. Pinset dan air bersih", "C. -", "D. -"]', 'B. Pinset dan air bersih'),
(24, 'Apa yang harus dilakukan jika korban tersambar petir?', '["A. -", "B. Segera periksa napas dan nadi, lakukan RJP jika perlu, dan bawa ke RS", "C. -", "D. -"]', 'B. Segera periksa napas dan nadi, lakukan RJP jika perlu, dan bawa ke RS'),
(24, 'Gunting yang bagian ujungnya tumpul (Gunting Verban) bertujuan untuk...', '["A. -", "B. Mencegah kulit korban terluka saat menggunting perban", "C. -", "D. -"]', 'B. Mencegah kulit korban terluka saat menggunting perban'),
(24, 'Kesehatan lingkungan perkemahan dijaga dengan cara membuat lubang sampah sedalam...', '["A. -", "B. 50-100 cm (agar tidak dibongkar hewan)", "C. -", "D. -"]', 'B. 50-100 cm (agar tidak dibongkar hewan)'),
(24, 'Obat yang digunakan untuk menolong sakit perut akibat maag adalah...', '["A. -", "B. Antasida", "C. -", "D. -"]', 'B. Antasida'),
(24, 'Mencuci luka dengan air sabun sangat disarankan khusus untuk luka akibat...', '["A. -", "B. Gigitan hewan (anjing/kucing) untuk cegah rabies", "C. -", "D. -"]', 'B. Gigitan hewan (anjing/kucing) untuk cegah rabies'),
(24, 'Prinsip utama penolong P3K adalah...', '["A. -", "B. Tenang, Cepat, Tepat, dan Tidak Panik", "C. -", "D. -"]', 'B. Tenang, Cepat, Tepat, dan Tidak Panik'),

-- ==========================================
-- BAB 99: Tambahan / Campuran
-- ==========================================
(99, 'Gerakan kepanduan di Indonesia resmi diakui dan menjadi anggota WOSM (World Organization of the Scout Movement) pada tahun...', '["A. -", "B. 1953", "C. -", "D. -"]', 'B. 1953'),
(99, 'Sifat kepramukaan yang berarti penyelenggaraannya disesuaikan dengan keadaan, kebutuhan, dan kepentingan masyarakat di negaranya adalah sifat...', '["A. -", "B. Nasional", "C. -", "D. -"]', 'B. Nasional'),
(99, 'Semboyan Sistem Among "Ing Madyo Mangun Karso" memiliki arti seorang Pembina harus mampu...', '["A. -", "B. Di tengah membangun kemauan/semangat", "C. -", "D. -"]', 'B. Di tengah membangun kemauan/semangat'),
(99, 'Tanda Kecakapan Khusus (TKK) tingkat tertinggi yang bentuknya segilima beraturan adalah tingkat...', '["A. -", "B. -", "C. Utama", "D. -"]', 'C. Utama'),
(99, 'Undang-Undang Republik Indonesia yang secara khusus mengatur tentang Gerakan Pramuka saat ini adalah...', '["A. -", "B. UU No. 12 Tahun 2010", "C. -", "D. -"]', 'B. UU No. 12 Tahun 2010'),
(99, 'Bapak Pandu Dunia (Chief Scout of the World) dan Bapak Pramuka Indonesia secara berurutan adalah...', '["A. -", "B. -", "C. Baden Powell dan Sri Sultan Hamengkubuwono IX", "D. -"]', 'C. Baden Powell dan Sri Sultan Hamengkubuwono IX'),
(99, 'Penggolongan usia Pramuka Penegak yang tepat adalah...', '["A. -", "B. -", "C. 16 - 20 tahun", "D. -"]', 'C. 16 - 20 tahun'),
(99, 'Meskipun lekat dengan dunia militer, ayah dari Baden-Powell sejatinya adalah seorang...', '["A. -", "B. Guru Besar Geometri di Universitas Oxford", "C. -", "D. -"]', 'B. Guru Besar Geometri di Universitas Oxford'),
(99, 'Suku-suku di Afrika memberikan julukan "Impeesa" kepada Baden-Powell, yang memiliki makna filosofis...', '["A. -", "B. -", "C. Serigala yang tidak pernah tidur", "D. -"]', 'C. Serigala yang tidak pernah tidur'),
(99, 'Buku mahakarya Baden-Powell yang ditujukan khusus untuk golongan pemuda (Rover Scout) pada tahun 1922 berjudul...', '["A. -", "B. -", "C. -", "D. Rovering to Success"]', 'D. Rovering to Success'),
(99, 'Kalung manik-manik kayu (Wood Badge) yang dikalungkan pada Pembina Pramuka lulusan kursus lanjutan berasal dari kalung pimpinan suku Afrika bernama...', '["A. -", "B. -", "C. Dinizulu", "D. -"]', 'C. Dinizulu'),
(99, 'Pada batu nisan makam Baden-Powell di Nyeri, Kenya, terdapat tanda jejak kepanduan berupa lingkaran dengan titik di tengah yang memiliki arti rahasia...', '["A. -", "B. Saya telah pulang", "C. -", "D. -"]', 'B. Saya telah pulang'),
(99, 'Pasukan kavaleri pertama yang ditempati Baden-Powell saat bertugas ke India dengan pangkat Pembantu Letnan adalah...', '["A. -", "B. -", "C. 13th Hussars", "D. -"]', 'C. 13th Hussars'),
(99, 'Buku Scouting for Boys secara struktural dibagi ke dalam 26 bab khusus yang oleh Baden-Powell disebut dengan istilah...', '["A. -", "B. Cerita Api Unggun (Campfire Yarns)", "C. -", "D. -"]', 'B. Cerita Api Unggun (Campfire Yarns)'),
(99, 'Simpul yang paling tepat digunakan untuk menyambung dua utas tali yang ukurannya TIDAK SAMA besar dan dalam keadaan kering adalah...', '["A. Simpul Anyam (Sheet Bend)", "B. -", "C. -", "D. -"]', 'A. Simpul Anyam (Sheet Bend)'),
(99, 'Prinsip konservasi dalam Cerita Api Unggun ke-15 melarang pandu membunuh binatang apa pun, KECUALI...', '["A. -", "B. -", "C. Ketika terancam bahaya keselamatan atau terpaksa untuk bertahan hidup", "D. -"]', 'C. Ketika terancam bahaya keselamatan atau terpaksa untuk bertahan hidup'),
(99, 'Tokoh orang suci pelindung Inggris yang dijadikan simbol ksatria kaum pandu di seluruh dunia (diperingati setiap 23 April) karena keberaniannya menumpas naga adalah...', '["A. -", "B. Santo George (St. George)", "C. -", "D. -"]', 'B. Santo George (St. George)'),
(99, 'Tindakan yang Paling Tepat jika pakaian yang dikenakan tiba-tiba tersambar api menurut panduan P3K Scouting for Boys adalah...', '["A. -", "B. -", "C. Berguling-guling di tanah atau membungkus rapat dengan selimut tebal", "D. -"]', 'C. Berguling-guling di tanah atau membungkus rapat dengan selimut tebal'),
(99, 'Inspirasi utama Baden-Powell tentang pentingnya pemuda bermula dari pasukan anak-anak saat pengepungan kota Mafeking yang dipimpin oleh...', '["A. -", "B. Lord Edward Cecil", "C. -", "D. -"]', 'B. Lord Edward Cecil'),
(99, 'Mendirikan tenda di dasar cekungan (lembah sempit kering) sangat dilarang oleh aturan perkemahan tingkat lanjut karena risiko...', '["A. -", "B. -", "C. Terjebak banjir bandang jika hujan lebat turun di hulu", "D. -"]', 'C. Terjebak banjir bandang jika hujan lebat turun di hulu'),
(99, 'Agar pasak tenda menancap kuat dan tidak mudah tercabut oleh angin, kemiringan pasak ke dalam tanah harus membentuk sudut...', '["A. -", "B. 45-60 derajat berlawanan dengan arah tarikan tali tenda", "C. -", "D. -"]', 'B. 45-60 derajat berlawanan dengan arah tarikan tali tenda'),
(99, 'Celana berbahan Jeans/Denim dilarang keras dipakai untuk pendakian dan kemah alam bebas karena alasan medis, yaitu...', '["A. -", "B. Berat, menahan panas, dan sangat sulit kering jika basah sehingga memicu hipotermia", "C. -", "D. -"]', 'B. Berat, menahan panas, dan sangat sulit kering jika basah sehingga memicu hipotermia'),
(99, 'Penerapan prinsip "Pack it in, Pack it out" dalam manajemen sampah perkemahan berarti...', '["A. -", "B. -", "C. Membawa kembali turun semua sampah anorganik untuk dibuang ke tempat yang semestinya", "D. -"]', 'C. Membawa kembali turun semua sampah anorganik untuk dibuang ke tempat yang semestinya'),
(99, 'Simpul yang paling praktis untuk menautkan tali tenda pada pasak karena bisa ditarik ulur (dikencangkan/dikendurkan) tanpa melepas simpul adalah...', '["A. -", "B. Simpul Tali Tenda (Taut-line Hitch)", "C. -", "D. -"]', 'B. Simpul Tali Tenda (Taut-line Hitch)'),
(99, 'Jarak minimal yang direkomendasikan untuk membangun MCK (Mandi Cuci Kakus) darurat dari sumber mata air agar tidak mencemari lingkungan adalah...', '["A. -", "B. -", "C. 15 - 20 meter", "D. -"]', 'C. 15 - 20 meter'),
(99, 'Menurut standar telegrafi internasional, perbandingan durasi waktu antara ketukan "titik" (dot) dan "garis" (dash) dalam sandi Morse adalah...', '["A. -", "B. 1 : 3", "C. -", "D. -"]', 'B. 1 : 3'),
(99, 'Isyarat prosedural (Prosign) standar internasional untuk "Attention" atau tanda memulai pesan Morse yang sah adalah...', '["A. -", "B. -", "C. -.-.-", "D. -"]', 'C. -.-.-'),
(99, 'Jika huruf "O" adalah (---) dan "S" adalah (...), maka huruf "C" dalam kode morse adalah...', '["A. -.-.", "B. -", "C. -", "D. -"]', 'A. -.-.'),
(99, 'Jika memecahkan kata menggunakan "Sandi AND", hal pertama yang harus dilakukan adalah...', '["A. -", "B. Menghapus semua rangkaian huruf A-N-D yang berdekatan", "C. -", "D. -"]', 'B. Menghapus semua rangkaian huruf A-N-D yang berdekatan'),
(99, 'Huruf Q dan P dalam kode morse memiliki kombinasi garis yang mengecoh. Kombinasi yang benar secara berurutan untuk Q dan P adalah...', '["A. --.- dan .--.", "B. -", "C. -", "D. -"]', 'A. --.- dan .--.'),
(99, 'Isyarat bahwa pesan telah selesai seluruhnya (End of Message) dikirimkan dengan sandi...', '["A. -", "B. AR (.-.-.)", "C. -", "D. -"]', 'B. AR (.-.-.)'),
(99, 'Jika membaca peta topografi berskala 1:50.000 dan jarak dua titik di peta adalah 4 cm, maka jarak sebenarnya di medan adalah...', '["A. -", "B. 2 kilometer", "C. -", "D. -"]', 'B. 2 kilometer'),
(99, 'Garis kontur yang tergambar menjorok ke arah tempat yang lebih tinggi (membentuk huruf V terbalik) secara topografi merupakan...', '["A. -", "B. Lembah atau aliran air", "C. -", "D. -"]', 'B. Lembah atau aliran air'),
(99, 'Aturan baku "Golden Rule" dalam membaca koordinat Grid (UTM) 6 angka pada peta topografi adalah...', '["A. Baca garis vertikal dulu (Easting ke kanan), lalu garis horizontal (Northing ke atas)", "B. -", "C. -", "D. -"]', 'A. Baca garis vertikal dulu (Easting ke kanan), lalu garis horizontal (Northing ke atas)'),
(99, 'Perbedaan sudut putar yang ditunjukkan antara Utara Magnetis di jarum kompas dan Utara Peta (Grid) pada selembar peta disebut...', '["A. -", "B. -", "C. Deklinasi Magnetis", "D. -"]', 'C. Deklinasi Magnetis'),
(99, 'Alat mekanis dengan roda gigi kecil yang dijalankan menyusuri kelokan sungai di peta untuk menghitung jarak rute melengkung disebut...', '["A. -", "B. -", "C. -", "D. Curvimeter"]', 'D. Curvimeter'),
(99, 'Metode navigasi siang hari tanpa kompas menggunakan bayangan tongkat tegak lurus yang memanfaatkan pergerakan semu matahari disebut...', '["A. -", "B. Sundial (Metode Bayangan Matahari)", "C. -", "D. -"]', 'B. Sundial (Metode Bayangan Matahari)'),
(99, 'Dalam pemecahan Sandi Kotak 2, satu kotak kerangka silang dihuni oleh 3 huruf. Jika terdapat 2 titik di atas kerangka tersebut, maka itu menunjukkan huruf...', '["A. -", "B. -", "C. Ketiga", "D. -"]', 'C. Ketiga'),
(99, 'Sandi Kimia mengonversi kode Morse ke huruf. Jika kode aslinya adalah "H2O" (H=konsonan, O=vokal), maka morse yang terbentuk adalah...', '["A. -", "B. -", "C. --.", "D. -"]', 'C. --.'),
(99, 'Sandi yang menggunakan patokan waktu dengan selisih yang konstan (misal pukul 08.00 = A, 08.05 = B, 08.10 = C) disebut...', '["A. -", "B. -", "C. Sandi Jam", "D. -"]', 'C. Sandi Jam'),
(99, 'Sandi AZ menukar huruf awal dengan huruf akhir alfabet. Jika sandinya berbunyi "K", maka huruf aslinya adalah...', '["A. -", "B. P", "C. -", "D. -"]', 'B. P'),
(99, 'Sandi yang bentuk fisiknya memanjang menyerupai gerigi atau gelombang naik turun tanpa spasi putus disebut...', '["A. -", "B. -", "C. Sandi Ular / Sandi Gergaji", "D. -"]', 'C. Sandi Ular / Sandi Gergaji'),
(99, 'Dalam Sandi Koordinat tabel 5x5 dengan kata kunci "MERAH PUTIH", huruf A terletak pada titik temu kordinat...', '["A. Baris M, Kolom P", "B. -", "C. -", "D. -"]', 'A. Baris M, Kolom P'),
(99, 'Tindakan Pertolongan Pertama yang BENAR pada korban kecelakaan yang mimisan (hidung berdarah) adalah...', '["A. -", "B. -", "C. Menundukkan kepala ke depan dan menjepit cuping hidung selama 10 menit", "D. -"]', 'C. Menundukkan kepala ke depan dan menjepit cuping hidung selama 10 menit'),
(99, 'Rasio kompresi dada (pijat jantung) dan bantuan napas buatan pada RJP (Resusitasi Jantung Paru) untuk 1 orang penolong menurut standar medis terbaru adalah...', '["A. -", "B. 30 kompresi : 2 napas", "C. -", "D. -"]', 'B. 30 kompresi : 2 napas'),
(99, 'Penanganan keseleo (terkilir) di lapangan paling efektif menggunakan metode RICE, yang merupakan singkatan dari...', '["A. Rest, Ice, Compression, Elevation", "B. -", "C. -", "D. -"]', 'A. Rest, Ice, Compression, Elevation'),
(99, 'Alasan dilarangnya mengoleskan pasta gigi, mentega, atau kecap pada luka bakar melepuh adalah...', '["A. -", "B. Karena zat tersebut menahan/memerangkap sisa panas di dalam kulit dan memicu infeksi hebat", "C. -", "D. -"]', 'B. Karena zat tersebut menahan/memerangkap sisa panas di dalam kulit dan memicu infeksi hebat'),
(99, 'Jika digigit ular berbisa di tengah hutan, penanganan paling krusial sebelum di bawa ke RS adalah...', '["A. -", "B. -", "C. Imobilisasi (membidai area gigitan agar korban tidak bergerak sama sekali) untuk menahan laju penyebaran racun di kelenjar getah bening", "D. -"]', 'C. Imobilisasi (membidai area gigitan agar korban tidak bergerak sama sekali) untuk menahan laju penyebaran racun di kelenjar getah bening'),
(99, 'Luka tusuk yang diakibatkan oleh benda kotor berkarat (seperti paku) sangat berisiko fatal jika tidak dicuci bersih karena membawa bakteri penyebab...', '["A. -", "B. -", "C. Tetanus", "D. -"]', 'C. Tetanus'),
(99, 'Pembalut elastis berwarna coklat (Elastic Bandage) sangat direkomendasikan berada di dalam kotak P3K Pramuka karena berfungsi spesifik untuk...', '["A. -", "B. Membebat cedera persendian (terkilir/keseleo) agar tidak bengkak", "C. -", "D. -"]', 'B. Membebat cedera persendian (terkilir/keseleo) agar tidak bengkak');